### DISCUSSION TITLE
Workspaces background unexpectedly turns white

### DISCUSSION THREAD

**Discussion by jajo-11** [Alexays/Waybar#1814] [Q&A]
The background of Workspaces turns white but only if i have only chromium in that workspace.

Here is the workspaces part of my style.css

```css
#workspaces
{
    background: transparent;
    margin-top: 1px;
    margin-left: 2px;
    padding-bottom: 1px;
}
#workspaces button
{
    color: darkgray;
}
 #workspaces button.focused
{
    color: white;
}
 #workspaces button:hover {
    box-shadow: inherit;
    text-shadow: inherit;
    color: #58abb7;
    background: transparent;
}
 #workspaces button.urgent {
    background-color: #f77923;
}
```

![image](https://user-images.githubusercontent.com/2552188/65374696-068e4f80-dc8d-11e9-9d17-a3d60c2dd6c5.png)

As evident in the style.css the background should be transparent like the rest of the bar.

**Comment by Alexays** [comment]
Are your background white?

**Comment by jajo-11** [comment]
No. All my backgrounds are set to "transparent". This is how the Workspaces area looks like when chromium is not open:

![image](https://user-images.githubusercontent.com/2552188/65393914-a5977200-dd87-11e9-8a33-9682ecbebae5.png)

**Comment by Alexays** [comment]
Ahh i see, you must have the following block.
```css
window#waybar.chromium {
    background-color: #000000;
    border: none;
}
```

Or something like that, no?

**Comment by jajo-11** [comment]
No here is my full config:
https://gist.github.com/jajo-11/58076b36ad0b98aef5813f28b62c9ae5

By the way i am running:
-   Waybar v0.8.0
-   Chromium 77.0.3865.90 Arch Linux
-   sway version 1.2 (Aug 29 2019, Arch Linux)

**Comment by Alexays** [comment]
Are you using a theme?

**Comment by jajo-11** [comment]
What kind of theme?

**Comment by Alexays** [comment]
GTK system wide theme

**Comment by jajo-11** [comment]
I do, it is called Qogir, but i observe the same effect on other themes as "Clearlooks", "Crux" and "Raleigh"

**Comment by txtsd** [comment]
My waybar turns black, and I have `wlr/taskbar` enabled whose icons gain a huge white border, when Chromium is open. It doesn't happen with any other app on my system. Should I open a new issue for this?

EDIT: Looked at `style.css` and disabling the `.chromium` bit as mentioned above fixes the color problem, however, `wlr/taskbar`'s icons still gain a white border on the workspace Chromium is in.

EDIT2: Okay styling `taskbar button` like so fixed it for me:
```css
#taskbar button {
    border: 0px;
}
```
Just required a little rubberducking, heh.
