### DISCUSSION TITLE
Is there any way to modify the font color of tray only?

### DISCUSSION THREAD

**Discussion by HyperCherry** [Alexays/Waybar#2179] [Q&A] [answered]
I want to modify the font color of tray only and don't want to modify all  the font color of widgets.
I have tried
```css
#tray{
    color: #ffffff;
}

#tray menu{
    color: #ffffff;
}

#tray > .passive{
    color: #ffffff;
}

#tray > .active{
    color: #ffffff;
}

#tray > .needs-attention{
    color: #ffffff;
}
```
but it's doesn't attempted to be white(`#ffffff`).How to solve it?

**Comment by giomf** [comment]
Im also interested.
Currently my menu font color is quite the same as the background color which makes it really hard to read.
Would like to change it.

Did you manage to solve it?

**Comment by me-self** [comment]
The issue here is that you are changing the text color of the tray itself, not it's children (the buttons)

I've used the following to change the background color of the buttons on hover:

```
#tray menu *:hover {
    background: rgba(255,255,255,0.3);
}
```

To change the text color of the buttons you could probably do the following:

```
#tray menu * {
    color: #ff0000;
}
```

This likely isn't a 'good way' to be doing this since it changes *all* children (from what I've noticed it should matter *too much* as the buttons seem to be the only children, but it might not stay this way).

**Comment by distek** [comment, marked as answer]
Figured this out today:
https://github.com/Alexays/Waybar/issues/2569#issuecomment-1869651193


```css
#tray menu menuitem:hover {
  background-color: #000000;
  color: #ffffff;
}
```

Doc link for GTK's `menuitem`:
https://lazka.github.io/pgi-docs/Gtk-3.0/classes/MenuItem.html#class-details
