### DISCUSSION TITLE
How do I set the CSS styles for the "format-alt" format in the "network" module? I couldn't find any instructions on the wiki,.

### DISCUSSION THREAD

**Discussion by DreamMaoMao** [Alexays/Waybar#2411] [General]
And the following configurations didn't match successfully.

```css
#network.alt{
    background-color:#f9e2af ;
}

```
