### DISCUSSION TITLE
How to style workspace windows icons?

### DISCUSSION THREAD

**Discussion by chrisr87** [Alexays/Waybar#3197] [General]
Is there any way to style them? I'm using Hyprland and I tried to `GTK_DEBUG` the bar and it seems like the workspaces window icons are rendered together so I can't find a selector for the individual window icons. My desire is to be able to style icons for active windows differently than icons for inactive windows. The documentation only provides selectors for the workspace icons themselves but not the individual window icons.

For example in here, I see that we can select by title or class. But how do I select by whether the window is focused or not? Or is this impossible natively via the waybar config?
```
"hyprland/workspaces": {
  "format": "<sub>{icon}</sub>\n{windows}",
  "format-window-separator": "\n",
  "window-rewrite-default": "",
  "window-rewrite": {
    "title<.*youtube.*>": "", // Windows whose titles contain "youtube"
    "class<firefox>": "", // Windows whose classes are "firefox"
    "class<firefox> title<.*github.*>": "", // Windows whose class is "firefox" and title contains "github". Note that "class" always comes first.
    "foot": "", // Windows that contain "foot" in either class or title. For optimization reasons, it will only match against a title if at least one other window explicitly matches against a title.
    "code": "󰨞",
	},
  ...
}
```

**Comment by IdleSys** [comment]
do you mean something like this?

```css
/* .config/waybar/style.css*/
#workspaces button.active{
	color: @peach;
  	border-radius: 10px;
    padding-left: 8px;
    padding-right: 8px;
    animation: gradient_f 20s ease-in infinite;
    transition: all 0.3s cubic-bezier(.55,-0.68,.48,1.682);
}
```
