### DISCUSSION TITLE
How can I set worksaces font size

### DISCUSSION THREAD

**Discussion by PILIHU2022** [Alexays/Waybar#3204] [Q&A]
I try to set `workspaces` font size in `style.css`, like this
```css
#workspaces{
    background: #1C1C29;
    margin: 5px 5px 5px 5px;
    margin-left: 5px;
    margin-right: 5px;
    /* padding: 0px 5px 0px 0px; */
    padding-left: 0px;
    /* padding-right: 0px; */
    border-radius: 16px;
    border: solid 0px #f4d9e1;
    font-size: 25px;
    font-weight: normal;
    font-style: normal;
}
```
But it doesn't work
What can I do?

**Comment by Gremious** [comment]
Try

```css
#workspaces * {
    font-size: 25px;
}
```
