### DISCUSSION TITLE
[Question] Rounded bottom corners with waybar

### DISCUSSION THREAD

**Discussion by guttermonk** [Alexays/Waybar#3291] [Q&A] [answered]
Trying to put the final touches on my waybar and I was wondering how do you add an inside radius to the bottom corners of the waybar? Similar to this screenshot:

![image](https://github.com/Alexays/Waybar/assets/4753752/bf5ae361-ff8d-4294-9bf8-875cd1bfad93)

Same question asked [on reddit](https://www.reddit.com/r/swaywm/comments/1973c2g/rounded_display_corner_with_waybar/), but no correct answers posted yet. Any help is greatly appreciated.

**Comment by LukashonakV** [comment]
Hi @guttermonk , see my waybar styling. [Viktar's dot](https://gitlab.com/Viktar/dotfiles/-/blob/main/.config/waybar/style.css?ref_type=heads)
```css
window#waybar {
    background-color: @base01;
    border-bottom: 1px solid #181825;
    border-radius: 50px;
    transition-property: background-color;
    color: @base02;
}
```

**Reply by guttermonk** [reply]
Hi @LukashonakV, thank you for trying to help, but that css just gives a pill shaped rounded corner. That doesn't look anything like the screenshot above.

**Comment by guttermonk** [comment]
I've tracked the reference screenshot down:
https://lemmy.ml/post/11795990
https://github.com/Serpentian/AlfheimOS

Not sure where the waybar css file is in all these Nix dotfiles though.

**Comment by nobe4** [comment]
FWIW, I have found a way to do this like so:

```css
#privacy-item {
	padding: 2px;
	border-radius: 100px;
	box-shadow: 0 -5px @bg inset, 0 5px @bg inset;
}
```

<img width="153" height="39" alt="image" src="https://github.com/user-attachments/assets/e4057292-9d21-41d9-843c-9d89517dc75a" />


`@bg` needs to be defined somewhere, and all the px values are "best guesses", but that does what I want :)
