### DISCUSSION TITLE
GTK theme is screwing up tooltip styling

### DISCUSSION THREAD

**Discussion by poperigby** [Alexays/Waybar#3326] [Q&A]
I've been tearing my hair out trying to get this to work.

I switched to using [this]() GTK theme that has these CSS rules for tooltips:

```css
tooltip {
  border: none;
  background-clip: padding-box;
  padding: 6px 12px;
  box-shadow: none;
}

tooltip.background {
  background-color: rgba(20, 22, 23, 0.9);
  color: #ddc7a1;
  box-shadow: 0 2px 2.4px -1px rgba(0, 0, 0, 0.2),
    0 4px 3px 0 rgba(0, 0, 0, 0.14), 0 1px 6px 0 rgba(0, 0, 0, 0.12);
  border-radius: 6px;
  margin: 2px 6px 8px 6px;
}

tooltip > box {
  border-spacing: 6px;
}
```

This is my CSS for tooltips:

```css
tooltip {
    background: @bg;
    border-radius: 12px;
}

tooltip label {
    color: @text-color;
    font-size: 14px;
}
```

I want it to look like this:
![image](https://github.com/Alexays/Waybar/assets/20866468/a82b57df-045c-4b99-81f2-133ae75c5d6f)

But it looks like this:
![2024-06-03_22-31](https://github.com/Alexays/Waybar/assets/20866468/e115595c-5207-4335-98e5-50b52cde7d91)
