### DISCUSSION TITLE
How to get box for modules?

### DISCUSSION THREAD

**Discussion by enoryw** [Alexays/Waybar#4063] [Q&A]
How to get modules to have "boxes" with the text inside [like this](https://0x0.st/8O9n.png)?

Actually, I'm looking for ways to make the modules more visually distinct from each other without increasing height of the bar or the width of the modules. And preferably without making the text smaller or increasing the space between modules. It should be quite subtitle too.

I've been using `border-right` but it kind of looks ugly with a grid-like look (it might look better if it didn't take up the whole height).

Much appreciated.

P.S. I currently have `#memory.high { background-color: #FA5F55; color: #000000; }` to color the module's background when memory usage is high. This covers the whole background--is it possible to not cover the text portion and only the icon portion? It makes it hard to read the text even if I change the text color.

**Comment by TheElevatedOne** [comment]
You use the `margin-right` and `margin-left` CSS modifier.

Margin specifies the space between elements. Imagine two elements next to each other, ex.:
```css
element1 {
}
element2 {
}
```

Element 2 want to be further apart from Element 1 and it pushes it 5 pixels to the left, which can look like:
```css
element1 {
}
element2 {
  margin-left: 5px;
}
```
or
```css
element1 {
  margin-right: 5px;
}
element2 {
}
```

---

In my own waybar config, I can show this like this:

![2025-05-18-005935_hyprshot](https://github.com/user-attachments/assets/77e202df-755e-4f7b-9fc2-e2e6ea669690)

The right arrow is a module with this css:
```css
#custom-rp-lock {
  color: @lock;
  font-size: 20px;
}
```

If I change it to
```css
#custom-rp-lock {
  color: @lock;
  font-size: 20px;
  margin-left: 5px;
}
```
it looks like

![2025-05-18-010204_hyprshot](https://github.com/user-attachments/assets/7f8f9159-7daa-4ceb-88ec-fed4f9f40ddc)

---

This way you can push apart the elements, and to workaround the empty space between elements to have some background, you can group elements via the [Group Module](https://github.com/Alexays/Waybar/wiki/Module:-Group) and assign CSS to it.
