### DISCUSSION TITLE
Finally able to set up the icon separately using CSS

### DISCUSSION THREAD

**Discussion by galemwendar** [Alexays/Waybar#4150] [Show and tell]
I just want to share the joy and code, I searched for quite a long time and decided to just write.
Sorry if this is stupid or obvious but I hope it helps someone.

![изображение](https://github.com/user-attachments/assets/9076b100-9513-4646-b6db-fd11b3db5605)
config
```
    "pulseaudio": {
        "format": "{volume}%",
        "scroll-step": 5,
        "on-click": "pavucontrol",
        "ignored-sinks": ["Easy Effects Sink"]
    },
    "custom/pulseicon": {
        "format": ""
        }
```
style.css
```css

#pulseaudio {
    padding: 0 10px;
    margin: 0 10px;
    border: 1px solid rgba(100, 114, 125, 0.5);
    margin-left: 0px;
    border-left: none;
    border-top-left-radius: 0;
    border-bottom-left-radius: 0;
}

#custom-pulseicon{
	background: rgba(190, 80, 70, 1);
	color: #282c34;
	padding: 0 10px;
	margin-left: 10px;
	margin-right: 0;
	border: 1px solid rgba(100, 114, 125, 0.5);
	border-right: none;
	border-top-right-radius: 0;
	border-bottom-right-radius: 0;
}
```
