### DISCUSSION TITLE
Drop shadow of image and icons only

### DISCUSSION THREAD

**Discussion by benlavender** [Alexays/Waybar#4169] [Q&A]
This is my `style.css`:

```css
@define-color bg rgba(18, 18, 18, 1);
@define-color fg rgba(255, 255, 255, 0.95);
@define-color border rgba(50, 50, 50, 1);
@define-color hover rgba(18, 18, 18, 0.75);

window#waybar {
    background: @bg;
    color: @fg;
    font-family: 'CommitMono Nerd Font Propo';
    font-size: 16px;
    font-weight: bold;
    border-top: 1.5px solid @border;
    min-height: 0;
}

#network {
    padding: 0 1px;
}

#bluetooth {
    padding: 0 1px;
}

#pulseaudio {
    padding: 0 1px;
}

#custom-arch-start {
    background-image: url("/home/ben/.config/waybar/arch.png");
    background-repeat: no-repeat;
    background-position: center;
}

#custom-arch-start:hover {
	background-color: @border;
}
```

Config:

```json
{
    "position": "bottom",
    "height": 32,
    "modules-left": [
        "custom/arch-start"
    ],
    "modules-right": [
        "bluetooth",
        "network",
        "pulseaudio",
        "clock"
    ],
    "spacing": 8,
    "clock": { 
        "format": "{:%H:%M} "
    },
    "network": {
        "format-ethernet": "\udb81\udef3",
        "format-wifi": "\uf1eb",  
        "format-linked": "\udb81\udef5",
        "format-disconnected": "\udb83\udc9b",
        "tooltip-format-wifi": "{ifname} / {ipaddr}/{cidr} => {essid}",
        "tooltip-format-ethernet": "{ifname} / {ipaddr}/{cidr}"
    },
    "bluetooth": {
        "format-off": "\udb80\udcb2",
        "format-on": "\udb80\udcaf",
        "format-connected": "\uf293",
        "format-no-controller": "\udb80\udcb3"
    },
    "custom/arch-start": {
        "format": "     ",
        "tooltip": false
    },
    "pulseaudio": {
        "format": "{icon} {volume}%",
        "tooltip-format": "{desc} {volume}%",
        "format-bluetooth": "\udb82\udd70",
        "format-muted": "\ueee8",
        "format-source-muted": "\ueee8",
        "format-icons": {
            "alsa_output.platform-fe00b840.mailbox.stereo-fallback": "\uee58"
        }
    }
}
```

What I'm wanting to do is have something like a drop shadow around just the icons in the module and the .png image in the custom-arch-start. Is this possible?
