### DISCUSSION TITLE
Hiding hyprland/windows module when empty doesn't work

### DISCUSSION THREAD

**Discussion by NGB-Was-Taken** [Alexays/Waybar#4187] [Q&A]
config
```json
"modules-center": [
        "hyprland/window"
    ],
"hyprland/window": {
        "format": "{}",
        "icon": true
    }
```
css
```css
window#waybar.empty #window{
    background-color: transparent;
}
```
When switching to a workspace without a window, nothing seems to change. The background color is still the same as before. Wasn't sure if I was doing something wrong or something is broken, so, I decided to create a discussion instead of an issue.
