### ISSUE TITLE
Missing support for CSS variables

### ISSUE THREAD

**Issue by tasmo** [Alexays/Waybar#1049]
When I try to put variables in the CSS file I get the error `[error] style.css:1:1Invalid name of pseudo-class`.

Example:

```css
:root {
  --color1: #00ccff;
}

window#waybar {
  color: var(--color1);
}
```
