### ISSUE TITLE
Color or effect when resizing Sway window

### ISSUE THREAD

**Issue by mamutal91** [Alexays/Waybar#1059]
Someone who uses sway with waybar, can you tell me if you can change the color in the bar, while the sway is in resize mode?

**Comment by Alexays** [comment]
Yes — use the `sway/mode` module. It's empty in the default mode and displays the current binding-mode name (e.g. `resize`) whenever you're in a mode, and you style it via `#mode`:
```jsonc
// config
"sway/mode": { "format": " {}" }
```
```css
/* style.css */
#mode { background-color: #cc3333; color: #ffffff; padding: 0 10px; }
```
Add `sway/mode` to one of your `modules-*` lists and it'll light up in your chosen color while resizing (and disappear again afterwards). Closing, but feel free to reopen. 🙏
