### ISSUE TITLE
Second battery states style

### ISSUE THREAD

**Issue by soyuz2012** [Alexays/Waybar#1096]
How to set second battery states style (e.g. warning, critical) in CSS file?
Something like `#battery.warning.bat2:not(.charging)` is not working (for module `"battery#bat2"`) :disappointed:

**Comment by Alexays** [comment]
Named instances like `battery#bat2` are configured completely independently — the `warning`/`critical` classes come from that module's own `states` object (Waybar adds a CSS class for each matched state; see `ALabel::getState`). If your `states` block only lives on the base `battery` module, `bat2` never gets a `warning`/`critical` class, so the selector matches nothing.

Give the instance its own `states`:
```jsonc
"battery#bat2": {
  "bat": "BAT2",
  "states": { "warning": 30, "critical": 15 }
}
```
Then this works (class order in a selector is irrelevant in CSS):
```css
#battery.bat2.warning:not(.charging)  { color: orange; }
#battery.bat2.critical:not(.charging) { color: red; }
```
`bat2` is the class taken from the part after `#` in the module name, and `charging` is the lower-cased status. Closing — reopen if it still won't match. 🙏
