### ISSUE TITLE
How to style appindicator menus?

### ISSUE THREAD

**Issue by jpalus** [Alexays/Waybar#1102]
It appears that menus in appindicators (nm-applet, blueman) inherit some of styling from waybar ie font family and font color, while background and highlight colors come from gtk theme. Since I'm using bright font color in waybar and bright gtk theme it results in unreadable menus. Is there any way to style those menus independently of the rest of waybar?

**Comment by jpalus** [comment]
In case anyone's interested following worked for me:
```css
menu label {
    color: @theme_text_color;
    font-family: DejaVu Sans;
}
menu label:disabled {
    color: @insensitive_fg_color;
}
```
