### ISSUE TITLE
Feature request/question - gaps

### ISSUE THREAD

**Issue by rhajdacki** [Alexays/Waybar#123]
Is there a way to set transparent gaps around the bar?
Currently it seems setting margin on * or #waybar makes margin with the same background color as the one set on #waybar .
Also gaps option in bar section of Sway config does not seem to work.

**Comment by Alexays** [comment]
You can do something like this in your css file
```css
window#waybar {
    background: transparent;
}

window > box {
	margin: 10px;
    background: rgba(43, 48, 59, 0.5);
    border-bottom: 3px solid rgba(100, 114, 125, 0.5);
    color: white;
}
```
