### ISSUE TITLE
Window drop shadow

### ISSUE THREAD

**Issue by isshin1** [Alexays/Waybar#1296]
feature request : allow waybar window to have a drop shadow of its own.

Given that sway and wlroots based compositors arent providing shadow rendering by themselves, instead of making apps do it themselves, will it be possible to have this feature ?

**Comment by eneshecan** [comment]
Here is how you can achieve this:
```css
window#waybar {
    background-color: transparent;
    color: @white;
}

window#waybar > box {
    border-radius: 8px;
    margin: 4px 8px 8px 8px;
    padding: 0px 2px;
    background-color: rgba(32, 32, 32, 0.75);
    border-radius: 8px;
    box-shadow: 4px 4px 2px 1px #101010;
}
```
