### ISSUE TITLE
Window title for the rest of WMs.

### ISSUE THREAD

**Issue by freeconst** [Alexays/Waybar#1340]
Is it possible to make a window title module for other window managers like WayFire? At the moment there is a module for Sway only. This function is already included in "taskbar" as {title}, but then the titles of all windows are visible. It could simply be an option for the taskbar to display only the active window.

**Comment by bklaase** [comment]
Would it be possible to have a workaround using styling? To hide all inactive buttons with css? 
another option could be to implement a seperate 'format.active' and leaving other formats as empty string?

**Comment by bklaase** [comment]
So yeah, there is no way to 'hide' gtk elements in such a way that makes them not take up space (that I could find). But you can make them invisible. So for the title to be placed left as the last item, this solution sort of works:

![image](https://user-images.githubusercontent.com/8513117/198822954-83340237-35da-4441-93e9-f87f2f6eeb6d.png)

```css
#taskbar button {
  background: transparent;
  outline-color: transparent;
  border-color: transparent;
  color: transparent;
  box-shadow: none;
}

#taskbar button.active {
  color: #ffffff;
}
```

Would be really really great, if active-only could be implemented somehow .. :)

**Comment by phuhl** [comment]
@bklaase I got it to look pretty much ok with this CSS:

```css
#taskbar.title button {
  font-size: 0px;
  padding: 0px;
  margin: 0px;
}

#taskbar.title button.active {
  font-size: 14px;
}
```
