### ISSUE TITLE
sway: waybar background based on smart_gaps

### ISSUE THREAD

**Issue by primalmotion** [Alexays/Waybar#1349]
I've looked around but I could not find any issue related to this. I would like to be able to use a different style for the general background of waybar based on gaps. I use smart_gaps in sway that basically removes any gaps when there is only one window in a workspace. I usually set the waybar background transparent, but I would like to use a solid color when the windows actually "touch" waybar.

Is this something we can do and I missed it, or is it something we could add support for in waybar?

Awesome project otherwise!

**Comment by WuerfelDev** [comment]
I don't think it's currently possible
My 'solution' was to use a black-to-transparent gradient.

This works well for me:

    background: linear-gradient(0deg, rgba(0,0,0,0.05) 0%, rgba(0,0,0,0.6) 100%);

(https://gitlab.com/WuerfelDev/dotfiles/-/blob/master/dots/waybar/.config/waybar/style.css#L10)

![screenshot](https://user-images.githubusercontent.com/12686819/148376689-65106c5c-f0e3-4229-9871-119174e2dc50.png)

**Comment by WuerfelDev** [comment]
You should be able to change the `name` (which is essentially a css class) of the bar via IPC: https://github.com/Alexays/Waybar/wiki/Configuration#bar-config
Then in your style.css just add this: (assuming you set the name to 'singlewindow')
```css
window#waybar.singlewindow {
    background: black;
}
```


Then with a nice fade out transition:
```css
window#waybar {
    background: rgba(0,0,0,0);
    transition: background .3s;
}

window#waybar.singlewindow {
    background: rgba(0,0,0,1);
    transition: none;
}

```
