### ISSUE TITLE
Add "workspace focused but inactive" indicator to default CSS

### ISSUE THREAD

**Issue by sethidden** [Alexays/Waybar#1403]
This is related to #97

# The problem

Say I'm using the default CSS for waybar. 
When you have two monitors (eg. left and right), if you focus a workspace on the left monitor (eg. press $mod+1), the first workspace on the left monitor will become focused and receive the default "#workspaces button.focused" style which is:
![image](https://user-images.githubusercontent.com/5359825/150705258-1a984cc0-f4b3-42e8-8501-8e3b988c56a3.png)
```css
#workspaces button.focused {
    background-color: #64727D;
    box-shadow: inset 0 -3px #ffffff;
}
```
However, if I eg. press $mod+4, which would be a workspace currently on the right monitor, the left monitor's workspaces from the previous screenshot would become unfocused and look like this:
![image](https://user-images.githubusercontent.com/5359825/150705366-60b03b61-7d3d-4831-9520-d43ea0402518.png)

Now if my currently focused workspace is on the right monitor and I want to go back to the left monitor's currently displayed workspace it's difficult.  I know it's  either workspace 1 or workspace 3, but not really sure which one. There's no "this is the currently displayed workspace on this monitor, but it's not focused" indicator

# The proposed solution
Remove the existing `#workspaces button.focused` style then add the below snippet to Waybar's default CSS
```css
#workspaces button.focused.focused {
    background-color: #64727D;
    box-shadow: inset 0 -3px #ffffff;
}

#workspaces button.visible {
    box-shadow: inset 0 -3px #000000;
}
```
this results in:
![image](https://user-images.githubusercontent.com/5359825/150705590-84b3a7bb-1c2e-44ef-8895-25ecb3035454.png)
saying "hey this workspace is inactive but this is the one currently selected on this monitor"

Obviously any solution works, as I'm sure no one likes the ".focused.focused" trick here

# Misc
As outlined in #97, this is an easy few-line snippet the user can add on their own. However I believe this affects the initial user experience enough to provide this feature out of the box, as not knowing which workspace is selected on each monitor (thus being unable to quickly switch back to a given monitor) could be frustrating

**Comment by pocek** [comment]
Perhaps a cleaner option:
```css
#workspaces button.focused {
    /* ... */
}

#workspaces button.visible:not(.focused) {
    /* ... */
}
```

**Comment by tobsz** [comment]
> Perhaps a cleaner option:
> 
> ```css
> #workspaces button.focused {
>     /* ... */
> }
> 
> #workspaces button.visible:not(.focused) {
>     /* ... */
> }
> ```

Is something like this possible with `wlr/workspaces`? Or is there any other way to achieve this?

**Comment by thatanjan** [comment]
I am using hyprland with this: 
```css
#workspaces button.active {
  background-color: rgb(249, 226, 175);
  /* background-color: red; */
  color: #3a3b3c;
}

#workspaces button.visible:not(.active) {
  background-color: green;
  /* background-color: red; */
  color: #3a3b3c;
}
```

This is not working for me

**Comment by braun-steven** [comment]
> Perhaps a cleaner option:
> 
> ```css
> #workspaces button.focused {
>     /* ... */
> }
> 
> #workspaces button.visible:not(.focused) {
>     /* ... */
> }
> ```

Some recent update seems to have broken this solution.

I have

```css
/* Button */
#workspaces button {
    border-top: 1px solid transparent;
    border-bottom: 1px solid transparent;
    border-left: 1px solid transparent;
    border-right: 1px solid transparent;
    /* To compensate for the top border and still have vertical centering */
    padding-bottom: 2px;
    padding-left: 5px;
    padding-right: 5px;
    border-color: #333333;
    color: #888888;
    background-color: #222222;
}

/* Focused button */
#workspaces button.focused {
    border-color: #4c7899;
    color: #eceff4;
    background-color: #285577;
}

/* Focused button but on inactive monitor */
#workspaces button.visible:not(.focused) {
    border-color: #333333;
    color: #ffffff;
    background-color: #5f676a;
}
```

which used to work until a few days ago, I think. Now my inactive (visible, not focused, second monitor) workspace has the same color as all other unfocused workspaces.
