### ISSUE TITLE
Abnormal box model behavior with 

### ISSUE THREAD

**Issue by PAI5REECHO** [Alexays/Waybar#1498]
I'm confused as to why the blue buttons go outside their content region into the surrounding bar's `border`:
```css
window#waybar {
  background: orange;
  border-top: .6em solid red;
  border-bottom: .6em solid cyan;
}

#memory,
#cpu {
  border-bottom: 3pt solid green;
  padding: 0 calc(2em/3);
  background-color: blue;
}
```
