### ISSUE TITLE
Css Variables

### ISSUE THREAD

**Issue by weasnerb** [Alexays/Waybar#159]
Is there any way that we can get support for [Css Custom Properties (variables)?](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables)

I would love to import the generated css vars from pywal so that I can style waybar with the generated colors. It seems that the :root selector is not supported with whatever parsing system is being used in the project.

**Comment by Alexays** [comment]
In GTK you can do something like this
```css
@define-color custom rgb (181, 171, 156);

#clock {
	color: @custom
}
```
