### ISSUE TITLE
latest broke custom-<x> style

### ISSUE THREAD

**Issue by primalmotion** [Alexays/Waybar#1726]
Since the last merge galore, it seems something broke regarding custom modules styling.

This used to work (the icon was blinking in red) Now it does not. Whatever I put in #custom-recording css style seems to be totally ignored

```json
"custom/recording": {
	"interval": 2,
	"exec-if" : "pgrep wf-recorder",
	"exec": "echo 'recording'",
	"format": "\uf111",
	"tooltip": false
}
```

```css
@keyframes blink-recording {
	from { color: #ff2222; }
	to { color: #990000; }
}

#custom-forcedboot {
	padding: 0 8px 0 8px;
	min-width: 60px;
	animation-duration: 1s;
	animation-iteration-count: infinite;
	animation-direction: alternate;
        animation-name: blink-critical;
}
```
