### ISSUE TITLE
Clock colour is always gray

### ISSUE THREAD

**Issue by WhyNotHugo** [Alexays/Waybar#1761]
As of 0.9.14 and in 0.9.15, the clock's colour is always gray:

![image](https://user-images.githubusercontent.com/730811/199683078-33bb8267-d13f-416b-88ad-289c43c70d86.png)

Config is pretty unambiguous:

```css
#clock {
  color: #ffffff;
}
```

Full css: https://git.sr.ht/~whynothugo/dotfiles/tree/ba3f3e40/item/home/.config/waybar/style.css

Previously mentioned in https://github.com/Alexays/Waybar/issues/1759#issuecomment-1299970351

**Comment by dragove** [comment]
try
```css
button {
  color: white;
}
```
