### ISSUE TITLE
Hover effect on some modules

### ISSUE THREAD

**Issue by HarHarLinks** [Alexays/Waybar#1763]
After upgrading to 0.9.14 and beyond, I get the hover effect from the workspaces module also on some but not all other modules.
I've tried messing with the attributes from the wiki https://github.com/Alexays/Waybar/wiki/FAQ#the-workspace-buttons-have-a-strange-hover-effect like
```css
button:hover {
    box-shadow: inherit;
    text-shadow: inherit;
}
```
but it has no effect.

Please fix/add some documentation how to disable it.
