### ISSUE TITLE
Reduce repetition

### ISSUE THREAD

**Issue by darksilentcore** [Alexays/Waybar#1842]
Hello & thanks
```css
* {
    background: transparent;
    border-radius: 0px;
    border: none;
    box-shadow: none;
    font-family: JetBrains Mono, Material\-Design\-Iconic\-Font;
    font-size: 14px;
    text-shadow: none;
}

window#waybar {background-color: #212B30;}
#custom-menu {color: #BA68C8; padding-left: 16px; padding-right: 12px;}
#workspaces button {color: #4DD0E1; padding-left: 4px; padding-right: 4px;}
#workspaces button.focused {color: #EC407A;}
#cpu {color: #C4C7C5; padding-left: 12px; padding-right: 8px;}
#memory {color: #C4C7C5; padding-left: 8px; padding-right: 8px;}
#disk {color: #C4C7C5; padding-left: 8px; padding-right: 8px;}
#mpd {color: #C4C7C5; padding-left: 8px; padding-right: 8px;}
#mode {color: #4DD0E1; padding-left: 8px; padding-right: 8px;}
#custom-functions {color: #C4C7C5; padding-left: 8px; padding-right: 8px;}
#language {color: #C4C7C5; padding-left: 8px; padding-right: 8px;}
#pulseaudio {color: #C4C7C5; padding-left: 8px; padding-right: 8px;}
#clock {color: #C4C7C5; padding-left: 8px; padding-right: 8px;}
#custom-io {color: #C4C7C5; padding-left: 8px; padding-right: 16px;}
```
As you can see, several equal variables are set repeatedly
How can i set a global variable
but it can set different for exceptions?
like font-size or padding-left
thanks again
