### ISSUE TITLE
Waybar behaves differently for different GTK themes

### ISSUE THREAD

**Issue by scotabroad** [Alexays/Waybar#1851]
I've noticed that while I'm using the Rose-Pine-Moon GTK theme, my waybar winds up looking like this:
![20221129_12h06m55s_grim](https://user-images.githubusercontent.com/65510090/204627446-e11045e0-0070-429a-856c-2318b2520751.png)

The workspace indicator and tooltips are not what I would expect. Tooltips should be transparent according to my style.css.
But when I use the Nordic GTK theme instead with the same style.css, waybar looks like this:
![20221129_12h00m44s_grim](https://user-images.githubusercontent.com/65510090/204627510-229d7d45-a7ea-428d-905b-d638b73c3fd3.png)

And everything seems to be following my style.css file correctly
Shouldn't waybar look the same if all the color values for the tooltip and size of the workspace indicator are hard coded values? My style.css file currently looks like this:
```css
* {
    border: none;
    border-radius: 0;
    font-family: Ubuntu Nerd Font;
    font-size: 13px;
    min-height: 0;
}

window#waybar {
    background: transparent;
    color: #d9d7e1;
}

tooltip {
    background: alpha(#393552, 0.5);
    border-radius: 10px 10px 10px 10px;
    border: 1.5px solid #c4a7e7;
}

tooltip label {
    color: #d9d7e1;
}

/* -- Modules -- */
#custom-search,
#workspaces,
#window, 
#clock, 
#tray, 
#cpu, 
#memory, 
#temperature,
#pulseaudio, 
#battery,
#custom-power { 
    color: #d9d7e1;
    background: alpha(#393552, 0.9);
    border: 1.5px solid #c4a7e7;
    padding: 0 10px;
}

/* -- Left Modules -- */

#custom-search {
    border-radius: 20px 0px 0px 20px;
    border-right: 0px;
    margin-left: 10px;
}

#workspaces {
    padding: 0 0px;
    border-radius: 0px 20px 20px 0px;
    border-left: 0px;
}

#workspaces button {
    padding: 0 5px;
    border-radius: 20px 20px 20px 20px;
    background: transparent;
    color: #d9d7e1;
}

#workspaces button.active {
    background: #c4a7e7;
    color: #393552;
}

/* -- Center Modules -- */

#clock {
    border-radius: 20px;
}

/* -- Right Modules -- */

#tray {
    border-radius: 20px;
    margin-right: 15px;
    margin-left: 15px;
}

#cpu {
    border-radius: 20px 0px 0px 20px;
    border-right: 0px;
}

#memory, #temperature, #pulseaudio, #battery {
    border-right: 0px;
    border-left: 0px;
}

#temperature.critical {
    color: #eb6f92;
}

#battery.charging {
    color: #3e8fb0;
}

#battery.threes:not(.charging) {
    color: #eb6f92;
}

#battery.twos:not(.charging) {
    color: #eb6f92;
}

#battery.ones:not(.charging) {
    color: #eb6f92;
}

#custom-power {
    border-radius: 0px 20px 20px 0px;
    border-left: 0px;
    margin-right: 10px;
}
```
