### ISSUE TITLE
Ability to style tooltips

### ISSUE THREAD

**Issue by Reikimann** [Alexays/Waybar#1885]
^ Title. I don't know if its possible, but I can't seem to find anything on it.

**Comment by rubyowo** [comment]
You can style tooltips by using the `tooltip` for the box, and `tooltip label` for the text.

**Comment by bhepple** [comment]
A concrete example would really help those of us less familiar with the archanae of CSS terminology!!! Pretty please. Asking for a friend.

**Comment by Reikimann** [comment]
```css
tooltip {
  background-color: #fff;
}

tooltip label {
  color: #aaa;
}
```
