### ISSUE TITLE
river/tags module option to hide unoccupied tags

### ISSUE THREAD

**Issue by MelihDarcanxyz** [Alexays/Waybar#1915]
Hiding unoccupied tags on river would be nice. Tried that with css but I had nothing due to GTK CSS limitations.
So I'm wondering if this can be implemented on module level.

**Comment by dithpri** [comment]
The following CSS worked for me:
```css
#tags button:not(.occupied):not(.focused) {
	font-size: 0;
	min-width: 0;
	min-height: 0;
	padding: 0 0;
	border: 0;
}
```
