### ISSUE TITLE
river/tags module urgent class doesn't work

### ISSUE THREAD

**Issue by MelihDarcanxyz** [Alexays/Waybar#1916]
I configured it to have red labels when something urgent happens but it doesn't.

```json
"river/tags": {
		"num-tags": 10,
		"tag-labels": [
			1,
			2,
			3,
			4,
			5,
			6,
			7,
			8,
			9,
			10
		],
		"disable-click": false
	}
```

```scss
#tags {
	button {

		color: colors.$background-dark;
		padding: 2px 5px;

		&.occupied {
			color: colors.$foreground;
		}

		&:hover {
			color: colors.$cyan;
		}

		&.focused {
			color: colors.$pink;
		}

		&.urgent {
			color: colors.$red;
		}

	}
}
```
