### ISSUE TITLE
Regression on CSS class with the MPRIS module

### ISSUE THREAD

**Issue by bvergnaud** [Alexays/Waybar#2087]
Hello 👋🏻 

Following the recent patch to the MPRIS module which fixed the random segfaults (thanks again Alexays !) I resumed working on using it in my config. Playing around with it, I think I may have found a regression on the CSS class on that module. I have this configuration:

```css
#mpris {
    background: inherit;
    box-shadow: inset 0 -4px @dracula-purple-grey;
    margin: 0 4px;
    padding: 0 16px;
}

#mpris.Plexamp {
    box-shadow: inset 0 -4px @plex;
}

#mpris.paused, #mpris.stopped {
    box-shadow: inset 0 -4px @dracula-light-grey;
    color: @dracula-light-grey;
}
```

And the configuration for the `Plexamp` or `paused` classes are never applied. Digging around with the GTK inspector and comparing with other modules, it seems the classes are applied to the parent widget instead of the label.
I have an example with the CPU module for comparison but it seems all module behave like the CPU module so I'm guessing it's an error in the mpris module.

![20230404-225452](https://user-images.githubusercontent.com/9599845/229919985-34c065b2-d696-4c4d-a699-d887c8ef8a01.png)
![20230404-225526](https://user-images.githubusercontent.com/9599845/229919989-f144284d-cdbd-4fad-87e9-53c3788d9fa1.png)

I call it a regression because I'm pretty sure it did work when I first tried the module back when 0.9.17 was released. Right now I'm on master, on the latest commit.

```
❯ waybar --version
Waybar v0.9.17-124-g3d980f92 (branch 'master')
```
