### ISSUE TITLE
Default style.css workspaces button.focused broken on hyprland

### ISSUE THREAD

**Issue by YodaEmbedding** [Alexays/Waybar#2151]
On Hyprland, the focused workspace doesn't highlight with the default style.css.

To get it to work, I changed it from:
```css
#workspaces button.focused {
    background-color: #64727D;
    box-shadow: inset 0 -3px #ffffff;
}
```

To:
```css
#workspaces button.focused,
#workspaces button.active {
    background-color: #64727D;
    box-shadow: inset 0 -3px #ffffff;
}
```
