### ISSUE TITLE
Unmute on scroll

### ISSUE THREAD

**Issue by kugland** [Alexays/Waybar#2253]
When the sink is muted (as opposed to unmuted with 0 volume), scrolling up doesn’t unmute. I’m using pipewire and wireplumber.

**Comment by evyatark2** [comment]
You can use `on-scroll-up` and `on-scroll-down` like so:
```yaml
"wireplumber": {
        "on-scroll-up": "wpctl set-mute @DEFAULT_AUDIO_SINK@ 0; wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%+",
        "on-scroll-down": "wpctl set-mute @DEFAULT_AUDIO_SINK@ 0; wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%-"
}
```
