### ISSUE TITLE
Better documentation for custom modules

### ISSUE THREAD

**Issue by cmacrae** [Alexays/Waybar#232]
Hey @Alexays :wave: 

Thanks very much for Waybar!

I'd love to contribute some improved documentation for custom modules, as right now it's not clear to me how formatting works.  

If you're able to clarify the problem I'm not understanding, I'll gladly submit a PR.  

So, I'm putting together a little custom module to indicate if my VPN is active.
Based off the documentation on the Wiki, here's what I've put together:
`config` section  
```json
    "custom/openvpn": {
	"format": "{}",
	"max-length": 40,
	"interval": 10,
	"return-type": "json",
	"exec": "/path/to/script"
    }
```

`style.css` section  
```css
#openvpn {
    color: #665C54;
}

#openvpn.active {
    color: #95C085;
}

#openvpn.inactive {
    color: #FAC03B;
}

#openvpn.disabled {
    color: #665C54;
}
```

My script returns the following JSON payload based on different states of the VPN service:
```json
{
  "text": "",
  "tooltip": "active: running",
  "class": ".openvpn.active"
}
```
Where `class` changes per state. The intention being: the little icon (in `format`) just changes colour based on this.

Am I just misunderstanding how this is supposed to work? Or have I gotten some syntax wrong? It's not clear to me how `class`'s value should be formatted to influence appearance of the `format` section.  

Many thanks in advance for any guidance on this :pray: 
As mentioned; I'll happily submit a Wiki PR to get this clarified once I understand it better.
