### ISSUE TITLE
Module icon format changes sizes when switching fonts

### ISSUE THREAD

**Issue by Frontear** [Alexays/Waybar#2375]
As the title says, I'm currently trying to modify the pipewire module and adding some nerd font icons to make my bar look a little bit nicer to what im trying to achieve. I'm using some pretty trivial icons, attached an image of them here:

![image](https://github.com/Alexays/Waybar/assets/31909298/540d6ee0-a420-4816-b0b1-2f7d5a216531)

I'm running into a little bit of an issue where my icons are spreading the module out depending on which one is displaying. It's causing a lot of annoyance because I can't seem to find _anyone_ else whose having this issue. The nerd font I'm using is MesloLGS NF, and it is monospaced. I can't seem to understand why its happening, and i was wondering if you may have some idea whats going on. I'll attach a video of the issue below:

https://github.com/Alexays/Waybar/assets/31909298/c121ad78-7b98-4935-b573-f6addbfa80fc

My current workaround is to manually reduce font-size in certain places, but that can't be the correct way to fix this. I will also add my config and style, maybe I have done something wrong?

```jsonc
// https://www.nerdfonts.com/cheat-sheet

{
    "layer": "top",
    "position": "top",
    "margin": 8,
    "spacing": 15,
    "modules-left": [
	"custom/archlinux", "custom/padding", "wlr/workspaces"
    ],
    "modules-center": [
	"hyprland/window"
    ],
    "modules-right": [
	"network", "wireplumber", "backlight", "battery",
	"custom/padding",
	"clock" /*power_button*/
    ],

    // modules
    "custom/padding": {
	"format": "|"
    },
    "custom/archlinux": {
	"format": "\uf303"
    },
    "wlr/workspaces": {
	"on-click": "activate"
    },
    "hyprland/window": {},
    "network": {
	"format-wifi": "{icon}",
	"format-ethernet": "\udb80\ude00",
	"tooltip-format-wifi": "{essid} ({signalStrength}%)",
	"tooltip-format-ethernet": "{ipaddr}/{cidr}",
	"format-disconnected": "\udb82\udd2e",
	"format-icons": [
	    "\udb82\udd1f", "\udb82\udd22", "\udb82\udd25", "\udb82\udd28"
	]
    },
    "wireplumber": {
	"format": "{icon}",
	"format-muted": "\udb81\udf5f",
	"format-icons": [
	    "\udb81\udd7f", "\udb81\udd80", "\udb81\udd7e"
	],
	"tooltip-format": "{volume}%"
    },
    "backlight": {
	"format": "{icon}",
	"format-icons": [
	    "\udb81\udee9", "\udb86\ude4e", "\udb86\ude4f", "\udb86\ude50", "\udb86\ude51", "\udb86\ude52", "\udb86\ude53", "\udb86\ude54", "\udb86\ude55", "\udb86\ude56", "\udb81\udee8"
	],
	"tooltip-format": "{percent}%"
    },
    "battery": {
	"interval": 5, // how long it takes to go from discharging -> charging
	"tooltip-format-discharging": "{capacity}%, empty in {time}",
	"tooltip-format-charging": "{capacity}%, full in {time}",
	"states": {
	    "100": 100,
	    "90": 90,
	    "80": 80,
	    "70": 70,
	    "60": 60,
	    "50": 50,
	    "40": 40,
	    "30": 30,
	    "20": 20,
	    "10": 10,
	    "5": 5
	},
	"format-discharging-100": "\udb80\udc79",
	"format-charging-100": "\udb80\udc85",
	"format-discharging-90": "\udb80\udc82",
	"format-charging-90": "\udb80\udc8b",
	"format-discharging-80": "\udb80\udc81",
	"format-charging-80": "\udb80\udc8a",
	"format-discharging-70": "\udb80\udc80",
	"format-charging-70": "\udb82\udc9e",
	"format-discharging-60": "\udb80\udc7f",
	"format-charging-60": "\udb80\udc89",
	"format-discharging-50": "\udb80\udc7e",
	"format-charging-50": "\udb82\udc9d",
	"format-discharging-40": "\udb80\udc7d",
	"format-charging-40": "\udb80\udc88",
	"format-discharging-30": "\udb80\udc7c",
	"format-charging-30": "\udb80\udc87",
	"format-discharging-20": "\udb80\udc7b",
	"format-charging-20": "\udb80\udc86",
	"format-discharging-10": "\udb80\udc7a",
	"format-charging-10": "\udb82\udc9c",
	"format-discharging-5": "\udb84\udccd",
	"format-charging-5": "\udb82\udc9f",
	"format-plugged": "\udb86\udc35",
	"format-full": "\udb85\udfe2"
    },
    "clock": {
	"format": "{:%H:%M}"
    }
}
```

```css
* {
    font-family: "SF Mono Regular", "MesloLGS NF";
    font-size: 16px;
}

window#waybar {
    background-color: transparent;
}

.modules-left,
.modules-center,
.modules-right {
    padding: 4px 16px 4px 16px;
    border-radius: 24px;
    background-color: rgba(255, 255, 255, 0.1);
}

#custom-archlinux {
    color: rgb(73, 214, 255);
    padding-left: 4px;
    font-size: 24px;
}

#workspaces button {
    padding: 0 8px;
}

#workspaces button.active {
    border-radius: 16px;
    background-color: rgba(255, 255, 255, 0.25);
}

#workspaces button.visible {
    color: red;
}

#network,
#wireplumber,
#wireplumber.muted,
#backlight,
#battery
{
    padding-right: 8px;
    font-size: 24px;
}

#wireplumber {
    font-size: 16px;
}

#battery.discharging {
    font-size: 15px
}
```
