### ISSUE TITLE
Pseudo classes: before/after

### ISSUE THREAD

**Issue by Hubro** [Alexays/Waybar#2384]
Any reason Waybar doesn't support pseudo classes? This would make it so easy to add- and style icons based on classes, and it would basically remove the need for `<span ...>` Pango markup for styling icons properly.

This would be *much* nicer than the current method of having to embed the icons in the module text with brittle Pango markup:

```python
    # ...

    device_class = device_name.lower().replace(" ", "-")

    icon_mapping = {
        "speakers": "\udb81\udcc3",
        "headset": "\udb80\udece",
        "snowball": "\uf130",
    }

    try:
        icon = f"<span font='13' rise='-1500'>{icon_mapping[device_class]} </span>"
    except KeyError:
        icon = ""

    classes = [device_type, device_class]

    if muted:
        classes.append("muted")

    print(
        json.dumps(
            {
                "text": f"{icon}{text}",
                "class": classes,
            }
        ),
        flush=True,
    )
```

Instead I could just do:

```css
#custom-audio-output {
    /* ... */
}
#custom-audio-output.speakers::before {
    content: "\udb81\udcc3 ";
    font-size: 14pt;
}
#custom-audio-output.headset::before {
    content: "\udb80\udece ";
    font-size: 14pt;
}
```

It would be far more satisfying if I could write my modules to simply provide the right information and classes, then leave the presentation entirely up to Waybar and the style sheet.
