### ISSUE TITLE
possible to distinguish focused/occupied/empty workspaces?

### ISSUE THREAD

**Issue by teinpa** [Alexays/Waybar#2480]
with waybar-hyprland and wlr/workspaces
i was able to distinguish the state of each workspace with this in style.css

```
#workspaces button.persistent {
    padding: 0 5px;
    color: #737373;
}

#workspaces button {
    padding: 0 5px;
    color: #6ee2ff;
}

#workspaces button.active {
    padding: 0 5px;
    color: #e4609b;
}
```

737373 for persistent (and empty) workspace,
6ee2ff for occupied (but not focused) workspace,
and e4609b for currently focused workspace.

but with the updates coming to hyprland i wanted to future-proof my setup
so i installed waybar-git and switched wlr/workspaces with hyprland/workspaces.
and now i can get persistent and focused working but not occupied.

with many changes here and there, i'm not sure if i should be asking here or hyprland.
apologies if i'm asking the wrong place and thank you for such an awesome project.

**Comment by zjeffer** [comment]
I use this config to get roughly what you want:

```css
#workspaces {
    margin-right: 8px;
}

/* non-empty workspaces */
#workspaces button {
    background-color: #4c566a;
    /* Use box-shadow instead of border so the text isn't offset */
    box-shadow: inset 0 -3px transparent;

    color: #d8dee9;
    transition: all 0.2s ease;

    border: none;
    border-radius: 0;
}

#workspaces button:hover {
    /* transition-duration: .1s; */
    color: #eceff4;
    box-shadow: inset 0 -2px #ffffff;
    /* https://github.com/Alexays/Waybar/wiki/FAQ#the-workspace-buttons-have-a-strange-hover-effect */
    text-shadow: inherit;
}

/* non-empty persistent workspaces */
#workspaces button.persistent {
    background-color: #4c566a;
}

/* empty persistent workspaces */
#workspaces button.empty {
    background-color: #2e3440;
}

/* active or visible workspaces */
#workspaces button.active,
#workspaces button.visible {
    background-color: #4c566a;
    box-shadow: inset 0 -4px #eceff4;
}

#workspaces button.urgent {
    color: #bf616a;
}
```

Keep in mind the order of the css definitons is very important.
