### ISSUE TITLE
Tray module menu hover styling

### ISSUE THREAD

**Issue by Diaoul** [Alexays/Waybar#2569]
Is there a way to customize the tray menu in hover mode?
Currently it's background "system" blue and color white.

Something like this would be great:
```css
#tray menu-item:hover {
    color: red;
    background-color: green;
}
```

**Comment by AdsonCicilioti** [comment]
Try it:
```css
#tray > widget:hover {
    color: red;
    background-color: green;
}
```

**Comment by distek** [comment]
Some documentation on what the actual item is named would be fantastic.

Doing this at least changes the background color of the current item:
```css
#tray menu *:hover {
  background-color: @color7;
  color: @background;
}
```

But it'd be better to know what the actual name of the item in the list is.

**Comment by jerek** [comment]
I found how to get this working to set fonts and text color on hover! Those require styling the `label` element inside the `menuitem`. Like this:
```CSS
menuitem label {
    font-family: "ClarityCity";
    font-weight: 500;
}
menuitem:hover label {
    color: #ffffff;
}
```

**Comment by juracy** [comment]
Testing with network manager applet (nm-applet) I've succeded with this:

```css
window > menu > menuitem:hover,
window > menu > menuitem:hover > check,
window > menu > menuitem:hover > box,
window > menu > menuitem:hover > box > *,
window > menu > menuitem:hover > label,
window > menu > menuitem:hover > label > *,
window > menu > menuitem:hover > arrow
{
    background-color: @secondary;
    color: @on_secondary;
}
```

Incluinding sub-menus ...
