### ISSUE TITLE
hyprland/workspaces - no highlight on active spaces

### ISSUE THREAD

**Issue by BoopyTheFox** [Alexays/Waybar#2635]
### Issue
When **"persistent_workspaces": { }** in config.jsonc is set, all non-empty non-selected workspace don't get highlighted.

### Versions (affected at the time)
0.9.23, 0.9.24

### Other context
Archlinux repos, hyprland 0.30.0

style.css:
```css
...
/* Workspace not selected, and not empty */
#workspaces button {
    padding: 0 3px;
    background-color: transparent;
    color: @red;
}

/* Workspace not selected, and empty */
#workspaces button.persistent {
    background-color: transparent;
    color: #333333;
}

/* Selected workspace */
#workspaces button.active {
    background-color: @base; /*#64727D;*/
    color: #ffffff;
    box-shadow: inset 0 -3px @pink;
}

#workspaces button:hover {
    background: rgba(0, 0, 0, 0.2);
    box-shadow: @crust;
    color: @mauve;
}

#workspaces button.urgent {
    background-color: #eb4d4b;
    color: white;
}
...
```

config.jsonc:
```jsonc
...
     "hyprland/workspaces": {
        "active-only": false,
        "disable-scroll": true,
        "warp-on-scroll": false,
        "sort-by-number": true,
        "persistent_workspaces": {
          "1": ["eDP-1"], 
          "2": ["eDP-1"], 
          "3": ["eDP-1"], 
          "4": ["eDP-1"], 
          "5": ["eDP-1"], 
          "6": ["eDP-1"], 
          "7": ["eDP-1"], 
          "8": ["eDP-1"], 
          "9": ["eDP-1"], 
          "10": ["eDP-1"], 
          "101": ["DP-1"], 
          "102": ["DP-1"], 
          "103": ["DP-1"], 
          "104": ["DP-1"], 
          "105": ["DP-1"], 
          "106": ["DP-1"], 
          "107": ["DP-1"], 
          "108": ["DP-1"], 
          "109": ["DP-1"], 
          "110": ["DP-1"] 
        },
     "format": "{icon}", //use "{name}: {icon}" to display numbers
     "format-icons": {
        "1": "",
        "2": "",
        "3": "",
        "4": "",
        "5": "",
        "6": "",
        "7": "",
        "8": "",
        "9": "",
        "10": "",
        "101": "",
        "102": "",
        "103": "",
        "104": "",
        "105": "",
        "106": "",
        "107": "",
        "108": "",
        "109": "",
        "110": "",
        "urgent": "",
        "focused": "",
        "default": ""
         }
     },
...
```

hyprland.conf:
(persistent flag doesnt make a difference)
```conf
# Set workspaces for 1st monitor
workspace = 1, monitor:eDP-1, persistent:true, default:true
workspace = 2, monitor:eDP-1, persistent:true
...
workspace = 9, monitor:eDP-1, persistent:true
workspace = 10, monitor:eDP-1, persistent:true

# Set workspaces for 2nd monitor
workspace = 101, monitor:DP-1, persistent:true, default:true
workspace = 102, monitor:DP-1, persistent:true
...
workspace = 109, monitor:DP-1, persistent:true
workspace = 110, monitor:DP-1, persistent:true
```

### Workaround at 03.11.2022
downgraded to waybar 0.9.22

**Comment by BendTheKn33** [comment]
I have the same issue. Occupied workspaces are no longer highlighted in version 0.9.23 and 0.9.24. last version that still worked is 0.9.22

@BoopyTheFox  persistent_workspaces is deprecated, use persistent-workspaces

**Comment by Axenide** [comment]
Same here.

**Comment by zjeffer** [comment]
I'm not sure what you mean with "highlighted", can you explain what you expect to see and what you actually see?

I don't get any problems with the latest version, here is my style.css:

```css
/* non-empty workspaces */
#workspaces button {
    background-color: #4c566a;
    /* Use box-shadow instead of border so the text isn't offset */
    box-shadow: inset 0 -3px transparent;

    color: #d8dee9;
    transition: all 0.2s ease;

    border: none;
    border-radius: 0;
}

#workspaces button:hover {
    /* transition-duration: .1s; */
    color: #eceff4;
    box-shadow: inset 0 -2px #ffffff;
    /* https://github.com/Alexays/Waybar/wiki/FAQ#the-workspace-buttons-have-a-strange-hover-effect */
    text-shadow: inherit;
}

/* non-empty persistent workspaces */
#workspaces button.persistent {
    background-color: #4c566a;
}

/* empty persistent workspaces */
#workspaces button.empty {
    background-color: #2e3440;
}

/* active or visible workspaces */
#workspaces button.active,
#workspaces button.visible {
    background-color: #4c566a;
    box-shadow: inset 0 -4px #eceff4;
}

#workspaces button.urgent {
    color: #bf616a;
}
```

**Comment by zjeffer** [comment]
I think it's because I use `empty` for empy persistent workspaces, and `persistent` for occupied persistent workspaces. I don't immediately see why this would cause problems if you don't have the `empty` class in style.css, though.

**Comment by Axenide** [comment]
> I think it's because I use `empty` for empy persistent workspaces, and `persistent` for occupied persistent workspaces. I don't immediately see why this would cause problems if you don't have the `empty` class in style.css, though.

Indeed, that was the issue. This CSS was working **before** the update:
```css
#workspaces {
  background: black;
  border-radius: 10px;
  padding: 5px 8px;
  margin: 10px;
  box-shadow: 0px 0px 3px rgba(0,0,0,1);
}

#workspaces button {
	border-radius: 0px;
	color: @white;
	/* transition: all 0.25s ease-in-out; */
}

#workspaces button.persistent {
	color: @brblack;
}

#workspaces button.active {
  color: @brgreen;
  text-shadow:
    0.25px 0.25px 0 @brgreen,
    -0.25px 0.25px 0 @brgreen,
    -0.25px -0.25px 0 @brgreen,
    0.25px -0.25px 0 @brgreen;
}

#workspaces button:hover {
	background-color: transparent;
	color: @brgreen;
}
```

Adding `#workspaces button.empty` solved the issue:
```css
#workspaces {
  background: black;
  border-radius: 10px;
  padding: 5px 8px;
  margin: 10px;
  box-shadow: 0px 0px 3px rgba(0,0,0,1);
}

#workspaces button {
	border-radius: 0px;
	color: @white;
	/* transition: all 0.25s ease-in-out; */
}

#workspaces button.persistent {
	color: @white;
}

#workspaces button.empty {
    color: @brblack;
}

#workspaces button.active {
  color: @brgreen;
  text-shadow:
    0.25px 0.25px 0 @brgreen,
    -0.25px 0.25px 0 @brgreen,
    -0.25px -0.25px 0 @brgreen,
    0.25px -0.25px 0 @brgreen;
}

#workspaces button:hover {
	background-color: transparent;
	color: @brgreen;
}
```

**Comment by kurtnettle** [comment]
> > I think it's because I use `empty` for empy persistent workspaces, and `persistent` for occupied persistent workspaces. I don't immediately see why this would cause problems if you don't have the `empty` class in style.css, though.
> 
> Indeed, that was the issue. This CSS was working **before** the update:
> 
> ```css
> #workspaces {
>   background: black;
>   border-radius: 10px;
>   padding: 5px 8px;
>   margin: 10px;
>   box-shadow: 0px 0px 3px rgba(0,0,0,1);
> }
> 
> #workspaces button {
> 	border-radius: 0px;
> 	color: @white;
> 	/* transition: all 0.25s ease-in-out; */
> }
> 
> #workspaces button.persistent {
> 	color: @brblack;
> }
> 
> #workspaces button.active {
>   color: @brgreen;
>   text-shadow:
>     0.25px 0.25px 0 @brgreen,
>     -0.25px 0.25px 0 @brgreen,
>     -0.25px -0.25px 0 @brgreen,
>     0.25px -0.25px 0 @brgreen;
> }
> 
> #workspaces button:hover {
> 	background-color: transparent;
> 	color: @brgreen;
> }
> ```
> 
> Adding `#workspaces button.empty` solved the issue:
> 
> ```css
> #workspaces {
>   background: black;
>   border-radius: 10px;
>   padding: 5px 8px;
>   margin: 10px;
>   box-shadow: 0px 0px 3px rgba(0,0,0,1);
> }
> 
> #workspaces button {
> 	border-radius: 0px;
> 	color: @white;
> 	/* transition: all 0.25s ease-in-out; */
> }
> 
> #workspaces button.persistent {
> 	color: @white;
> }
> 
> #workspaces button.empty {
>     color: @brblack;
> }
> 
> #workspaces button.active {
>   color: @brgreen;
>   text-shadow:
>     0.25px 0.25px 0 @brgreen,
>     -0.25px 0.25px 0 @brgreen,
>     -0.25px -0.25px 0 @brgreen,
>     0.25px -0.25px 0 @brgreen;
> }
> 
> #workspaces button:hover {
> 	background-color: transparent;
> 	color: @brgreen;
> }
> ```

I also faced the same issue. They haven't updated the wiki yet.

**Comment by zjeffer** [comment]
I think anyone can update the wiki, be the change you want to see in the world ;)

**Comment by BoopyTheFox** [comment]
## Solution
Use `#workspaces button.empty` for empty workspaces.
`persistent` - for non-empty, non-active workspaces
`active` and `visible` for active and visible workspaces

**Comment by greeid** [comment]
sorry for bumping this old post but I'm trying to implement the same thing but with circles and I can't wrap my head around how to work with the special characters (icons from this point onward)?
The above example works fine if you don't have icons for workspace indicator but how would you accomplish the same thing but with icons
This is what I could build up 
```txt
"hyprland/workspaces": {
	"active-only": false,
	"all-outputs": true,
	"format": "{icon}",
	"show-special": false,
	"on-click": "activate",
	"on-scroll-up": "hyprctl dispatch workspace e+1",
	"on-scroll-down": "hyprctl dispatch workspace e-1",
	"persistent-workspaces": {
		"1": [],
		"2": [],
		"3": [],
		"4": [],
		"5": [],
		"6": [],
		"7": [],
		"8": [],
		"9": [],
		"10": [],
	},
	"format-icons": {
		"active": "",
		"default": "",
		"urgent": "",
	},
},
```
```css
#workspaces button {
  color: @white;
  background-color: @module-bg;
  padding: 4px;
}

#workspaces button.active {
  color: @module-bg;
  background-color: @white;
}

#workspaces button.persistent {
  background-color: @module-bg;
  color: @white;
}

#workspaces button.empty {
  color: @white;
}
#workspaces button.urgent {
  color: @red;
}
```
Now I want a filled circle as a occupied worspace but I can't get my head around how I can accompish that?
From what I can gather, I can only show colors but no icon as indicator for occupied workspace

**Comment by Axenide** [comment]
Hi @greeid, the config is different now. Let me give you an example for what you want to achieve. This is actually a modified version of my Waybar.
```jsonc
"hyprland/workspaces": {
  "disable-scroll": false,
  "on-scroll-up": "hyprctl dispatch workspace -1",
  "on-scroll-down": "hyprctl dispatch workspace +1",
	"format": "{icon}",
	"format-icons": {
    "active": "",
    "default": "",
    "urgent": "",
	},
  "persistent-workspaces": {
       "*": 10
  }
},
```

**Comment by greeid** [comment]
Thanks @Axenide for the reply but what I wanted to accomplish was that it should have ` ` as the active, ` ` as default/empty and ` ` as occupied workspace but I could only change the color for the occupied workspace and not the icons?

Or is it not possible in waybar??

**Comment by Axenide** [comment]
@greeid Of course you can change the icon color. Here is a CSS that should work:
```css
#workspaces button {
	color: white;
}

#workspaces button.persistent {
	color: white;
}

#workspaces button.empty {
    color: gray;
}

#workspaces button.active {
  color: green;
}

#workspaces button:hover {
	color: green;
}
```
