### ISSUE TITLE
pulseaudio-slider module not available even if it's advertised on the release notes

### ISSUE THREAD

**Issue by StayPirate** [Alexays/Waybar#2645]
I followed the instruction on the [wiki](https://github.com/Alexays/Waybar/wiki/Module:-PulseAudio-Slider). But I get the following warning:
```
[2023-11-06 12:37:43.169] [warning] module pulseaudio-slider: Unknown module: pulseaudio-slider
```
Am I wrong or this module is available since [v0.9.23](https://github.com/Alexays/Waybar/releases/tag/0.9.23)? I'm on v0.9.24.

@Syndelis

**Comment by Syndelis** [comment]
I'm sorry, there appears to be a typo in the wiki. Swap `pulseaudio-slider` for `pulseaudio/slider`

**Comment by StayPirate** [comment]
Now it works, thanks. BTW regardless how I set  `"orientation"`, `"horizontal"` or `"vertical"` the slider is always shown vertical.

![image](https://github.com/Alexays/Waybar/assets/37073343/fa6853fa-9816-4fdd-abd7-91606806efe3)

**Comment by StayPirate** [comment]
pardon, I had to adjust the suggested CSS in order to get it `"horizontal"`. If you don't mind, I would mention that in the wiki and/or the man page.

**Comment by StayPirate** [comment]
FTR, I changed 

```css
#pulseaudio-slider trough {
    min-height: 80px;
    min-width: 10px;
    border-radius: 5px;
    background-color: black;
}
```
to
```css
#pulseaudio-slider trough {
    min-height: 10px;
    min-width: 80px;
    border-radius: 5px;
    background-color: black;
}
```
