### ISSUE TITLE
Incomprehensible outline

### ISSUE THREAD

**Issue by Mauladen** [Alexays/Waybar#2660]
When hovering over the waybar panel, there is such a stroke only around the number 1, I tried many options but did not solve the problem

![20231111_000022.jpg](https://github.com/Alexays/Waybar/assets/12824589/16fecd64-9aea-4abe-972a-34a1a75f454d)

```css
* {
    border: none;
    border-radius: 0;
    font-family: "JetBrainsMono Nerd Font";
    font-weight: bold;
    font-size: 16px;
    min-height: 0;
}

window#waybar {
    background: rgba(21, 18, 27, 0);
    color: #f6f7fc;
}

tooltip {
    background: #1e1e2e;
    opacity: 0.8;
    border-radius: 10px;
    border-width: 2px;
    border-style: solid;
    border-color: #11111b;
}

tooltip label{
    color: #cdd6f4;
}

#workspaces button {
    padding: 5px;
    color: #f6f7fc;
    margin-right: 5px;
}

#workspaces button.active {
    color: #000000;
    background: #a6e3a1;
    border-radius: 10px;
}

#workspaces button:hover {
    background: #11111b;
    color: #cdd6f4;
    border-radius: 10px;
}

#custom-launch_wofi,
#custom-launch_firefox,
#custom-launch_thunderbird,
#custom-launch_thunar,
#custom-launch_kitty,
#custom-lock_screen,
#custom-light_dark,
#custom-power_btn,
#custom-power_profile,
#custom-weather,
#custom-myhyprv,
#window,
#cpu,
#disk,
#custom-updates,
#memory,
#clock,
#battery,
#pulseaudio,
#network,
#tray,
#temperature,
#workspaces,
#idle_inhibitor,
#backlight {
    background: rgba(21, 18, 27, 0);
    opacity: 1;
    padding: 0px 8px;
    margin: 0px 3px;
    border: 0px;
}

#temperature.critical {
    color: #e92d4d;
}

#workspaces {
    padding-right: 0px;
    padding-left: 5px;
}

#window {
    border-radius: 10px;
    margin-left: 0px;
    margin-right: 0px;
}

#custom-launch_firefox, 
#custom-launch_thunderbird,
#custom-launch_thunar,
#custom-launch_wofi,
#custom-launch_kitty,
#custom-weather {
    margin-left: 0px;
    border-right: 0px;
    font-size: 24px;
    margin-right: 20px;
}

#custom-launch_firefox, 
#custom-launch_kitty {
    font-size: 20px;
}
```
