### ISSUE TITLE
:Hover effects not working

### ISSUE THREAD

**Issue by Cicin2837512** [Alexays/Waybar#2691]
I just created a little module in my waybar that opens up rofi when I click on it 
``` json
"custom/rofi": {
  "exec": "echo '   '",
  "on-click": "rofi -show drun",
  "on-click-right": "rofi -show run"
},
```
``` css
#custom-rofi {
  background-color: @color2;
  border-radius: 5px;
  box-shadow: inset 0 -3px @color1;
  padding-right: 5px;
}
#custom-rofi:hover {
  background-color: @color3; /* this line is the only change I made */
  border-radius: 5px;
  box-shadow: inset 0 -3px @color1;
  padding-right: 5px;
}
```
The problem is that the `#custom-rofi:hover` part just doesn't seem to do anything when I hover over the module and I have no idea why because that's just a normal css functionality..
