### ISSUE TITLE
[Question] How to do stepped corners?

### ISSUE THREAD

**Issue by isiko** [Alexays/Waybar#2708]
I'm trying to recreate the 37C3 theme, and as per their [styleguide](https://events.ccc.de/congress/2023/infos/styleguide/styleguide.pdf) corners should be stepped.

Heres an example:

![20231130_13h57m08s_grim](https://github.com/Alexays/Waybar/assets/44641688/d99a71e7-c6fe-4121-ae32-70ebbd66522c)

In their Website they do this by using a `clip-path`, but when trying to copy the CSS to my Waybar config, Waybar can't read the CSS. Is this just not possible with Waybar or is there a workaround to this?

Here's the example from their Website:
```CSS
.btn {
  clip-path:polygon(0px 6px,6px 6px,6px 0px,calc(100% - 6px) 0,calc(100% - 6px) 6px,100% 6px,100% calc(100% - 6px),calc(100% - 6px) calc(100% - 6px),calc(100% - 6px) 100%,6px 100%,6px calc(100% - 6px),0 calc(100% - 6px));
  font-weight:500;
  letter-spacing:0.1em
}
```
