### ISSUE TITLE
hyprland/workspaces window icons sometimes disappear

### ISSUE THREAD

**Issue by flip-rossi** [Alexays/Waybar#2802]
When using the hyprland/workspaces modules in Waybar with Hyprland, sometimes the icon of a specific window will disappear for no apparent reason, and I can move the window around workspaces or monitors and it won't fix. However, if I open a new window with the same class and title, the icon will be there.

Example (there is a Firefox client in the "12" workspace but it's icon doesn't show up):  
![2024-01-04_10:48:42](https://github.com/Alexays/Waybar/assets/45897447/4d4e256c-9235-4910-8af2-185f5cd97c79)  

One way I found to force this bug is to pin a floating window and then switch workspaces, but it also occurs seemly randomly in other situations I wasn't able to find patterns for.

I'm using FiraCode Nerd Font and Hyprland's split-monitor-workspaces plugin, if that makes any difference.

If I run `hyprctl clients` the window shows as normal:
```
Window 5583bc153850 -> Mozilla Firefox:
	mapped: 1
	hidden: 0
	at: 967,37
	size: 941,1031
	workspace: 12 (12)
	floating: 0
	monitor: 1
	class: firefox
	title: Mozilla Firefox
	initialClass: firefox
	initialTitle: Mozilla Firefox
	pid: 2607
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
	focusHistoryID: 2
```

My "hyprland/workspaces" field in config.jsonc:
```jsonc
    "hyprland/workspaces": {
         "all-outputs": false,
         "on-scroll-up": "hyprctl dispatch workspace e+1",
         "on-scroll-down": "hyprctl dispatch workspace e-1",

         "format": "[{name} {windows} ]",
         "format-window-separator": "  ",
         "window-rewrite-default": "",
         "window-rewrite": {
             // https://www.nerdfonts.com/cheat-sheet and https://fontawesome.com/icons
             "class<Alacritty>": "",
             "class<Pcmanfm>": "",
             "class<com.github.weclaw1.ImageRoll|nomacs>": "",
             "title<(.*[$%#] *)?nvim.*>": "",
             "title<(.*[$%#] *)?([hb]|nv)top.*>": "",
             "class<firefox>": "",
             "class<discord>": "",
             "title<Discord.*>": "",
             "title<.[0-9]+. Discord.*>": " °",
             "title<Signal>": "󰍡",
             "title<WhatsApp.*>": "",
             "title<.[0-9]+. WhatsApp.*>": "°",
             "title<(.* - )?(.[0-9]+. )?YouTube.*>": "",
             "title<.* - Gmail .*>": "󰊫",
             "class<obsidian>": "󱞁",
             "class<ONLYOFFICE Desktop Editors>": "󰈙",
             "class<calibre-.*>": "",
             "class<org.qbittorrent.qBittorrent>": "",
             "class<org.kde.kdeconnect.*>": "",
             "class<mpv>": "",
             "class<vlc>": "󰕼",
             "class<Gimp-.*>": "",
             "class<steam.*>": "󰓓", //  for FontAwesome
             "class<steam> title<Friends List>": "",
             "class<steam_app_[0-9]+>": "󰮂",
             "title<Winetricks.*>": "󰡶",
             "class<lutris>": "🦦",
             "class<Spotify>": "",
             "class<jetbrains-idea(-ce)?>": "",
             "class<Code>": "󰨞",
             "class<com.obsproject.Studio|zoom>": "",
             "class<io.github.whoozle.android-file-transfer>": "",
             "class<(Chromium)|(Chrome)>": "",
         },
```

Rules in style.css that affect the workspaces region (it's pretty much the default config):
```css
* {
    font-family: FiraCode Nerd Font;
    font-size: 13px;
}

window#waybar {
    background-color: rgba(43, 48, 59, 0.5);
    border-bottom: 3px solid rgba(100, 114, 125, 0.5);
    color: #ffffff;
    transition-property: background-color;
    transition-duration: .5s;
}

window#waybar.hidden {
    opacity: 0.2;
}

window#waybar.termite {
    background-color: #3F3F3F;
}

window#waybar.chromium {
    background-color: #000000;
    border: none;
}

button {
    /* Use box-shadow instead of border so the text isn't offset */
    box-shadow: inset 0 -3px transparent;
    /* Avoid rounded borders under each button name */
    border: none;
    border-radius: 0;
}

/* https://github.com/Alexays/Waybar/wiki/FAQ#the-workspace-buttons-have-a-strange-hover-effect */
button:hover {
    background: inherit;
    box-shadow: inset 0 -3px #ffffff;
}

#workspaces button {
    padding: 0 5px;
    background-color: transparent;
    color: #ffffff;
}

#workspaces button:hover {
    background: rgba(0, 0, 0, 0.2);
}

#workspaces button.active {
    background-color: #64727D;
    box-shadow: inset 0 -3px #ffffff;
}

#workspaces button.urgent {
    background-color: #eb4d4b;
}

#window,
#workspaces {
    margin: 0 4px;
}

/* If workspaces is the leftmost module, omit left margin */
.modules-left > widget:first-child > #workspaces {
    margin-left: 0;
}

/* If workspaces is the rightmost module, omit right margin */
.modules-right > widget:last-child > #workspaces {
    margin-right: 0;
}
```
