### ISSUE TITLE
Widget text doesn't respect css content boundaries 

### ISSUE THREAD

**Issue by vibeisveryo** [Alexays/Waybar#2895]
Hello,

I'm running into a fairly annoying issue trying to style waybar. Here is my stylesheet:

```css
* {
  font-family: FontAwesome, Red Hat Display, sans-serif;
  font-size: 12pt;
  min-height: 0;
}
                                                         
window#waybar {
  background: rgba(43, 48, 59, 0.9);
  color: white;
}
                                                         
widget {
  border-left: 5px solid rgba(0, 0, 0, 0.25);
  padding-left: 5px;
  border-right: 5px solid rgba(0, 0, 0, 0.25);
  padding-right: 5px;
}
```

The text in the widgets seems to respect the widget boundaries themselves, but not internal CSS boundaries - so padding just doesn't work, and the text/content flows into the borders:

![image](https://github.com/Alexays/Waybar/assets/27565096/8fae85dd-0e22-40fb-b419-15dbf6182245)

Am I misunderstanding something about Waybar styling?
