### ISSUE TITLE
Tray module spacing option breaks hover when in group drawer.

### ISSUE THREAD

**Issue by JacksonBrienen** [Alexays/Waybar#2906]
Currently I am using tray within a group's drawer, when spacing is set within the tray module if I hover between the gap of the first and second tray icon the drawer collapses.
Relevant Config:
```json
"custom/expand": {
    "tooltip": false,
    "format": "\uf0d9"
},

"tray": {
    "spacing": 8
},

"group/minimized": {
    "orientation": "horizontal",
    "modules": ["custom/expand", "tray"],
    "drawer": {
        "transition-duration": 500,
        "children-class": "minimized"
    }
}
```
Relevant Styling:
```css
#custom-expand {
    min-width: 25px;
}

#tray {
    margin: 0;
    padding: 0;
    margin-left: 3px;
}

#group-minimized {
    border-left: solid;
    border-left-width: 0.5;
}
```

Demo:
![waybar-tray-demo](https://github.com/Alexays/Waybar/assets/88233698/2275d8fa-679e-48a3-a672-0b6eaf91e8ae)

I have tried a lot in fixing this, including referencing Issue #2569, which uses menu and menuitem tags in the css selector, but I have so far failed to get either of these to work. My solution is not very clean, but gets the job done, I use the `#tray *` selector and set a left margin.
Working Config:
```json
"custom/expand": {
    "tooltip": false,
    "format": "\uf0d9"
},

"tray": {},

"group/minimized": {
    "orientation": "horizontal",
    "modules": ["custom/expand", "tray"],
    "drawer": {
        "transition-duration": 500,
        "children-class": "minimized"
    }
}
```
Working Styling:
```css
#custom-expand {
    min-width: 25px;
}

#tray {
    margin: 0;
    padding: 0;
}

#tray * {
    margin-left: 8px;
}

#group-minimized {
    border-left: solid;
    border-left-width: 0.5;
}
```
It is important to note that I have not been able to get this selector to work with the hover pseudo class.
Working Demo:
![waybar-tray-working-demo](https://github.com/Alexays/Waybar/assets/88233698/c4d87ac0-79da-4f2e-b752-ea5b245ebd5a)

Running waybar version 0.9.24 on Arch Linux with Hyprland.
