### ISSUE TITLE
css display/gradiant support for cava

### ISSUE THREAD

**Issue by realsnick** [Alexays/Waybar#2995]
not sure how doable it is but was thinking of something like this:
![image](https://github.com/Alexays/Waybar/assets/1440852/922d9d09-4b5e-4913-b5a9-2a6f5cb9b52b)

```css
#cava {
  color: transparent;
  background: linear-gradient(to bottom, #4CAF50 0%, #4CAF50 50%, #FFA500 50%, #FFA500 75%, #FF0000 75%, #FF0000 100%);
  display: inline-block;
}

```
