### ISSUE TITLE
Styles for `sway/window` do not work

### ISSUE THREAD

**Issue by crabvk** [Alexays/Waybar#3069]
waybar: 10.0
sway: 1.9
wlroots: 17.1

I think the issue started with release of  waybar version 10.0. As [wiki](https://github.com/Alexays/Waybar/wiki/Styling) shows I use the style
```css
label#window {
    margin-left: 16px;
    color: #818384;
}
```
It worked with previous version, but now it doesn't.

**Comment by y0nei** [comment]
Same issue for me but for `#workspaces button.persistent`

**Comment by crabvk** [comment]
I've just noticed that the following styles work
```css
#window {
    margin-left: 16px;
}

#window > * {
    color: #818384;
}
```
So, maybe it's the wiki that needs to be updated.
