### ISSUE TITLE
window#waybar.empty doesn't work anymore

### ISSUE THREAD

**Issue by tienbuigia** [Alexays/Waybar#3079]
I was able to use this snippet
```css
window#waybar.empty {
  background: none;
}
```
to remove waybar background when there is no windows open before, but after updated to the new version, I couldn't anymore.

`waybar -v`
> Waybar v0.10.0

Thank you.

**Comment by MahouShoujoMivutilde** [comment]
> v0.10.0

Plain `.empty` wasn't working long before 10 for me.

Try

```css
window#waybar.empty #window {
  background: transparent;
}

```

Works for me.
