### ISSUE TITLE
`sway/workspaces`: Styles for persistent workspaces don't work in `0.10.0`

### ISSUE THREAD

**Issue by y0nei** [Alexays/Waybar#3086]
After the update to the newest `0.10.0` version, styles like
```css
#workspaces button.persistent { color: @dark; }
```
no longer work, while they did just fine on version `0.9.24`
