### ISSUE TITLE
Only able to set one font feature

### ISSUE THREAD

**Issue by hlmos** [Alexays/Waybar#3100]
After trying to set more than one stylistic set and starting waybar I get a junk value error at the end of font-feature-settings, even though it's the correct syntax. I have the following config section:
```css
*{
	border: none;

	font-family: VictorMono Nerd Font Mono;
	font-feature-settings: "ss02", "ss07";
	font-weight: bold;
	font-size: 14px;
}
```
If I try to set the features separately, it works perfectly, but it seems the line only allows for a single string to be applied.
