### ISSUE TITLE
Waybar playerctl module no space after ...

### ISSUE THREAD

**Issue by mobsenpai** [Alexays/Waybar#3115]
# [NOT AN ISSUE]
Look I am really sorry if I am not asking it at the right place but I am really desperate for this rn.

> This is how playerctl module normally looks when the title doesn't exeed the max-length
![image](https://github.com/Alexays/Waybar/assets/92603465/cde68ec3-fe94-447f-a690-2502aeae0c05)

> But when max-length is exeeded
![image](https://github.com/Alexays/Waybar/assets/92603465/b36a0318-9ff7-49db-a0fd-c2208230ca27)

### ❓: There is no space after the ... (3 dots) I have tried adding paddings and margins but still the same result. What am I missing here?

> Full bar if incase it helps
![image](https://github.com/Alexays/Waybar/assets/92603465/25ed4949-ddbd-4901-98cd-1f131149b173)

> NOTE: I am on nixos and this is the output file so ignore the nix store links it just targets to an executable

## waybar config
```json
[
  {
    "clock": {
      "format": "<span background='#83a598' foreground='#1d2021'> 󱑆 </span><span background='#458588' foreground='#ffffff'> {:%a %b %d - %I:%M %p} </span>",
      "format-alt": "<span background='#83a598' foreground='#1d2021'> 󱑆 </span><span background='#458588' foreground='#ffffff'> {:%H:%M} </span>",
      "tooltip-format": "<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>"
    },
    "cpu": {
      "format": "<span background='#fabd2f' foreground='#1d2021'>  </span><span background='#3c3836' foreground='#d79921'> {usage}% </span>"
    },
    "custom/playerctl": {
      "exec": "/nix/store/mmq0si6l3g1yvbl47n74ys9imf67qm3w-playerctl-2.4.1/bin/playerctl -a metadata --format '{\"text\": \"{{markup_escape(title)}}\", \"tooltip\": \"{{playerName}} : {{markup_escape(title)}}\", \"alt\": \"{{status}}\", \"class\": \"{{status}}\"}' -F",
      "format": "{icon}<span background='#3c3836' foreground='#b16286'> {} </span>",
      "format-icons": {
        "Paused": "<span background='#d3869b' foreground='#1d2021'> 󰎈 </span>",
        "Playing": "<span background='#d3869b' foreground='#1d2021'>  </span>"
      },
      "max-length": 20,
      "on-click": "/nix/store/mmq0si6l3g1yvbl47n74ys9imf67qm3w-playerctl-2.4.1/bin/playerctl play-pause",
      "on-click-middle": "/nix/store/mmq0si6l3g1yvbl47n74ys9imf67qm3w-playerctl-2.4.1/bin/playerctl previous",
      "on-click-right": "/nix/store/mmq0si6l3g1yvbl47n74ys9imf67qm3w-playerctl-2.4.1/bin/playerctl next",
      "return-type": "json"
    },
    "custom/weather": {
      "exec": "/nix/store/048nhrvk2liq1sw35i56jf067xzyxdpi-wttrbar-0.6.0/bin/wttrbar --location Bihar --hide-conditions",
      "format": "<span background='#b8bb26' foreground='#1d2021'>  </span><span background='#3c3836' foreground='#98971a'> {}° </span>",
      "interval": 3600,
      "return-type": "json",
      "tooltip": true
    },
    "exclusive": true,
    "fixed-center": true,
    "hyprland/window": {
      "format": "{title}",
      "max-length": 40,
      "seperate-outputs": true
    },
    "hyprland/workspaces": {
      "disable-scroll": true,
      "format": "{name}",
      "on-click": "activate"
    },
    "layer": "top",
    "margin-bottom": 0,
    "margin-left": 0,
    "margin-right": 0,
    "margin-top": 0,
    "memory": {
      "format": "<span background='#8ec07c' foreground='#1d2021'> 󰍛 </span><span background='#689d6a' foreground='#3c3836'> {}% </span>"
    },
    "modules-center": [
      "custom/playerctl"
    ],
    "modules-left": [
      "hyprland/workspaces",
      "hyprland/window"
    ],
    "modules-right": [
      "custom/weather",
      "memory",
      "cpu",
      "clock",
      "tray"
    ],
    "position": "top",
    "spacing": 10,
    "tray": {
      "reverse-direction": true,
      "spacing": 6
    }
  }
]
```

## waybar style.css
```css
* {
  all: unset;
  font-family: 'monospace';
  font-size: 10pt;
  font-weight: bold;
}

tooltip {
  background: #282828;
  border: 1px solid #3c3836;
  border-radius: 8px;
  color: #a89984;
}

tooltip label {
  margin: 2px;
}

/* Waybar window */
window#waybar {
  background: #282828;
  color: #a89984;
}

/* Left Modules */
.modules-left {
  padding-left: 2px;
}

/* Right Modules */
.modules-right {
  padding-right: 2px;
}

/* Modules */
#clock,
#cpu,
#custom-playerctl,
#custom-weather,
#workspaces,
#window,
#memory,
#tray {
  padding: 2px 2px;
}

/* Workspaces */
#workspaces {
  background: #282828;
  color: #a89984;
}

#workspaces button {
  background: #282828;
  color: #a89984;
  min-width: 20px;
}

#workspaces button.active {
  background: #fe8019;
  color: #1d2021;
}

#workspaces button.urgent {
  background: #fb4934;
  color: #ffffff;
}

/* Window */
#window {
  color: #98971a;
  font-weight: normal;
}

/* Systray */
menu {
  background: #282828;
  border: 1px solid #3c3836;
  border-radius: 8px;
  color: #a89984;
}

menu separator {
  background: #3c3836;
}

menu menuitem {
  background: transparent;
  padding: 8px;
}

menu menuitem:hover {
  background: #fe8019;
  color: #1d2021;
}

menu menuitem:first-child {
  border-radius: 8px 8px 0 0;
}

menu menuitem:last-child {
  border-radius: 0 0 8px 8px;
}

menu menuitem:only-child {
  border-radius: 8px;
}
```

**Comment by ordy** [comment]
The padding is there, but probably just don't see it because you have set the background color inside the span in your config instead of using the css file. The background color inside your span only wraps around the text, not the whole custom module.

What it should look like if you change color to notice the padding:
![sc_746](https://github.com/Alexays/Waybar/assets/22659443/d4fb549f-eb97-43a5-98a8-92af3bc550c5)

**Comment by mobsenpai** [comment]
Oh I also noticed that but couldn't pinpoint my next step. So I have to add background color to custom-playerctl module?

**Comment by ordy** [comment]
Basically you just need to add this in your css styles file:

```css
#custom-playerctl {
    background-color: #3c3836;
}
```

And probably make some change to your padding too, because that would add a 2px padding of that same color on the left of your icon (which has a different color).

**Comment by mobsenpai** [comment]
Got it. Lemmy try it and then i shall update it here.

**Comment by mobsenpai** [comment]
> Basically you just need to add this in your css styles file:
> 
> ```css
> #custom-playerctl {
>     background-color: #3c3836;
> }
> ```
> 
> And probably make some change to your padding too, because that would add a 2px padding of that same color on the left of your icon (which has a different color).

---

![image](https://github.com/Alexays/Waybar/assets/92603465/6ebf11b3-1e77-4daa-8847-d332e9ae561e)

Ok that does work and I can add padding if I want but the padding makes the text off-centered so I will leave it at that **BUT** As you can see the reason why I didn't add the background color through style.css file was bcz it filled the whole module and you can see the edges not matching with the icon's background. 

Any idea what should I do to solve this?

**Comment by ordy** [comment]
> Any idea what should I do to solve this?

By using margin offset instead of padding (the left margin will recenter the module because it push it back after adding the 2px padding on the right of your title).

```css
#custom-playerctl {
	background-color: #3C3836;
	padding: 0px 2px 0px 0px;
	margin: 2px 0px 2px 2px;
}
```
