### ISSUE TITLE
[Bug] hyprland/workspaces: Active workspace not updated when a screen is disconnected

### ISSUE THREAD

**Issue by max-ishere** [Alexays/Waybar#3121]
# Steps to reproduce

1. Log into Hyprland
2. Attach 2 screens to a machine and make sure both are showing the desktop.
3. Start waybar with this config:

config.json
```json
[{
  "modules-left": [ "hyprland/workspaces" ],
  "hyprland/workspaces": { "move-to-monitor": true }
}]
```

style.css
```css
#workspaces button {
  padding: 0 0.5em;
  margin: 0 0.25em;
  border-radius: 3px;

  border: none;
}

#workspaces button.active {
  border: 3px solid red;
}
```
4. Focus the workspace on one of the monitors
5. Disable some other monitor (bind lid switch works too)
```shell
hyprctl keyword monitor 'eDP-1,preferred,0x0,1'
```

# Expected result

After the monitor is disabled the bar shows the selected workspace with a red outline.

# Actual result

No workspace is highlighted as active until a workspace is switched.
