### ISSUE TITLE
Is there variables in waybar?

### ISSUE THREAD

**Issue by MubinMuhammad** [Alexays/Waybar#3191]
Hi, recently, I was checking if style.css supports variables or not. And it turns out that it doesn't. Here is the code I've written to check it:
```css
:root {
  --waybar-border-radius: 2;
}

waybar {
  background: #282828;
  border-radius: var(--waybar-border-radius)px solid black;
}
```
The following code didn't even launch waybar in the first place. You might ask when will you need it. Well, imagine this situation, you are writing a configurator and now, asking the user for a border radius they would prefer. How would you write it in css? If you don't have variables it would be hard to do. If you do though you can just prepend the following `:root` section.

I hope it's already added or it's simple to add.
Thanks.
