### ISSUE TITLE
Random top border on newly created workspaces

### ISSUE THREAD

**Issue by Chaspen** [Alexays/Waybar#3343]
In my stylesheet, I have the workspace module setup so that an animation plays on focus; and it works! However a weird side-effect of this is that a roughly 1-2px width border appears at the top of newly created work spaces for a few frames before going away.
![weird-issue](https://github.com/Alexays/Waybar/assets/25672211/06a7e800-a7dd-41c9-9407-957283e55f04)
As far as I know, there's nothing in my CSS that could cause this, however there may be something I'm missing and would like some insight into what I can do with the relevant CSS to fix this if possible:
```css
#workspaces button {
	background-color: transparent;
	background:transparent;	
	color: white;
	min-width: 30px;
	border-radius: 0px;
	transition: 0.2s;
}

#workspaces button.focused {
	border-top-width: 0;
	border-bottom-style: solid;
	border-bottom-width: 3px;
	border-top-width: 0px;
	padding-top: 3px;
	background: transparent;
}

#workspaces button:hover {
	/* disable annoying default hover properties */
	box-shadow: inherit;
	text-shadow: inherit;
	background: inherit;
	border: white;
	padding: 0 0px;
	/* actual shit i want */
	color: black;
	background-color: white;
}
```
