### ISSUE TITLE
[Niri] Ability to query `#window` by focused app ID

### ISSUE THREAD

**Issue by ThatOneCalculator** [Alexays/Waybar#3609]
While there is a way to see what the *only* window in a workspace is, it'd be really nice to be able to query it by the focused window instead.

This example is a bit rough, but it'd be nice to be able to have a different gradient per-app.

```css
#window.code {
	background: linear-gradient(to top right, #31748f, #1f1d2e);
}

#window.firefox
	background: linear-gradient(to top right, #BF616A, #1f1d2e);
}

/* so on and so forth */
```

![image](https://github.com/user-attachments/assets/95da35b2-36e6-42c4-b691-4e4e14667595)
