### ISSUE TITLE
[Niri] css query for last workspace

### ISSUE THREAD

**Issue by ThatOneCalculator** [Alexays/Waybar#3610]
Since I usually only work on one workspace, right now I'm doing

```css
#workspaces button#niri-workspace-1 {
	padding-left: 14px;
	border-radius: 10px 0 0 10px;
	margin-right: 0px;
}

#workspaces button#niri-workspace-2 {
	padding-right: 14px;
	border-radius: 0 10px 10px 0;
	margin-left: 0px;
}
```

To get this effect:

![image](https://github.com/user-attachments/assets/12233a0f-4156-4d4c-a5aa-8de79e300603)

But the moment I add another workspace, the effect breaks:

![image](https://github.com/user-attachments/assets/c9ffe2f7-c893-43c2-a80c-1f6b7c8723b7)

So a `#workspaces button#niri-workspace-last` would be great
