### ISSUE TITLE
Missing transparency in sway workspaces widget buttons

### ISSUE THREAD

**Issue by m00nwtchr** [Alexays/Waybar#3707]
I have transparency set on the background of waybar, however for some reason the buttons on the sway/workspaces widget don't display it correctly: 
![image](https://github.com/user-attachments/assets/623535b3-d6ad-4418-8d4a-37cd1d22f90f)

My CSS:
```css
@define-color background alpha(@color0, 0.8);
@define-color inactive darker(darker(@foreground));
@define-color active darker(@foreground);

window#waybar {
  border-radius: 10px;
  background: @background;
  color: @foreground;
}

#workspaces button {
  padding: 5px;
  color: @inactive;
  margin-right: 5px;
  background: @background;
}

#workspaces button.active {
  color: @active;
}

#workspaces button.focused {
  color: @active;
  background: @background;
}

#workspaces button.urgent {
  color: @color0;
  background: lighter(alpha(@active, 0.8));
}

#workspaces button:hover {
  background: @background;
  color: lighter(@active);
}
```
