### ISSUE TITLE
style workspaces on hover

### ISSUE THREAD

**Issue by bartekjaszczak** [Alexays/Waybar#3732]
Is it possible to change the style of the "workspaces" element on hover? Here's my problem:

I'd like the border colour of "workspaces" element to change on hover. I'm using below CSS snippet for that:

```css
#workspaces:hover {
  border-color: #ffd500;
  transition: 0.3s ease-out;
  opacity: 1.0;
}
```

it doesn't, however, work, when I hover on any particular workspace button inside the "parent" workspace element. On the screenshot, the border actually only changes colour when I hover the mouse in the dark area between the border and the button, but it doesn't work when I hover over the actual button (yellow "1"). I tried to extend the hover to all workspaces' children, but with no success.

![image](https://github.com/user-attachments/assets/d8d7e76a-dab0-423d-a9a8-cc57aadd9802)
![image](https://github.com/user-attachments/assets/05202d08-d958-4860-b566-5d739bc4fa63)
