### ISSUE TITLE
Color font problem ( not sure if this come from waybar )

### ISSUE THREAD

**Issue by Ogromny** [Alexays/Waybar#375]
Hi,
When I set a white Gtk theme, the font in popup tray app is white...

![issue in question](https://i.imgur.com/TNuPpwv.png)

Do you think this issue, is related to waybar, or maybe from sway ?

Sorry for my poor English.

**Comment by Alexays** [comment]
It's not Waybar's fault, surely related to your theme :)

**Comment by Ogromny** [comment]
Fixed. The problem came from my style "waybar"
```:css
* {
    color: #F5F5F5;
}
```

**Comment by cafehaine** [comment]
Yeah, seems like somehow waybar applies the gtk style to subprocesses (or whatever the popups are), since nowhere in my GTK config I have set a monospace font (default adwaita theme), but I set the font to a mono one in waybar

**Comment by zoresvit** [comment]
You can avoid overwriting GTK styles by replacing `*` with a selector specific to Waybar:
```css
window#waybar {
  border: none;
  border-radius: 0;
  font-family: "Iosevka";
  font-size: 18px;
}

window#waybar {
  background-color: rgba(46, 52, 64, 0.98);
  color: #d8dee9;
}
```

And I think the font defined in Sway config also overrides tray styles, so you can also explicitly set a different font using `#tray` selector. So to match my GTK theme which uses Dejavu Sans I also add:
```css
#tray {
  font-family: "Dejavu Sans";
}
```
