### ISSUE TITLE
How to decrease the space between icons 

### ISSUE THREAD

**Issue by janemba** [Alexays/Waybar#3815]
Hello,

I'm using `group` for some icons with a simple `CSS` style:
```
#hardware{
	 font-weight: normal;
         padding: 0px;
         margin: 0px;
	 color: @fg;
	 background-color: @bg;
}
```
I'm trying to reduce the space between icons but my style has no effects.
![Screenshot_2024-12-08_02 34 29](https://github.com/user-attachments/assets/72f39812-84ec-4908-8af0-e6669e379049)

**Comment by JarKz** [comment]
Try change `spacing` option in main config file.
You can read more here: https://github.com/Alexays/Waybar/wiki/Configuration

**Comment by janemba** [comment]
I checked for it but unfortunately, its the gap size between modules and not icons.

**Comment by JarKz** [comment]
I didn't seen that you meant `group`, my bad. Try `#hardware *` selector, should work if you mean the space between group's inner elements.

**Comment by janemba** [comment]
Thank you it works fine.

Unfortunately, with that selector I'm having a radius for all icons instead of having the radius only on the edges. Is there a way to preserve it ?

I tried to suppress and manually put the radius at the edges from the first and last icons:
```
#hardware * {
    border-radius: 0;
    font-weight: normal;
    padding: 0 3px;
    margin: 0 3px;
    color: @fg;
    background-color: @bg;
}

#power-profiles-daemon {
    border-bottom-left-radius: 20px;
    border-top-left-radius: 20px;
}

#battery {
    border-bottom-right-radius: 20px;
    border-top-right-radius: 20px;
}
```

But the radius is not appearing for those icons in the group.

**Comment by JarKz** [comment]
As I understand you right, you mean the radius of **group bar**. To have this, you can use `#hardware` selector as well:

```css
#hardware * {
    /* this radius option kinda useless but I leave here */
    border-radius: 0;
    font-weight: normal;
    padding: 0 3px;
    margin: 0 3px;
    color: @fg;
}

/* apply the radius only to group bar */
#hardware {
    border-radius: 20px;
    background-color: @bg;
}
```

And it should work fine if background applies only to the 'hardware' group bar and inner modules doesn't have background.
