### ISSUE TITLE
Can't change color of workspaces icons

### ISSUE THREAD

**Issue by KiraKyatto** [Alexays/Waybar#3843]
Hello, I recently tried to configure waybar on my arch hyprland but I'm not able to change the base color of the workspace icon. Here are my config files : 

`config` : 
```
{
        //Position TOP
        "layer": "top",
        "margin-top": 14,
        "margin-bottom": 0,

        //Load modules
        "include":["~/.config/waybar/modules.json"],

        //Modules LEFT
        "modules-left":[
                "clock",
                "wlr/taskbar",
        ],

        //Modules CENTER
        "modules-center":[
                "hyprland/workspaces",
        ],
}
```

`style.css` : 
```
@import "/home/alex/.cache/wal/colors-waybar.css";

* {
        border: none;
        border-radius: 0;
        font-size: 18px;
        background: transparent;
}

#workspaces button {
        padding: 0 5px;
        color: @color3;
}

.modules-center {
        background-color: @color1;
        border-radius: 15px;
        padding: 0 10px;
}
```

`modules.json` : 
```
{
        "clock":{
                "tooltip": true,
        },
        "hyprland/workspaces":{
                "persistent-workspaces": {"DP-1":[1,2,3], "HDMI-A-1":[1,2,3]},
                "format": "{icon}",
                "format-icons":{
                        "active": "",  //these two are icons from nerd fonts
                        "default": ""
                },
        },
}

```
Thanks to whoever tries to help me.

**Comment by msmafra** [comment]
To do this, you mean?


[waybar-tests.webm](https://github.com/user-attachments/assets/8921f0e7-e561-448c-9e05-06694d011fe0)

test.css
@import "palette.css";

* {
    border: none;
    border-radius: 0;
    font-size: 18px;
    background: transparent;
}

#workspaces button {
    padding: 0 5px;
    color: @tertiarycritical;
}

#workspaces button:hover {
    color: @quarternarytext;
}

#workspaces button:active {
    color: @tertiarynarytext;
}

#workspaces button.visible {
    color: @secondarytext;
}

.modules-center {
    background-color: @tertiarybackground;
    border-radius: 15px;
    padding: 0 10px;
}

test.jsonc
{
    //Position TOP
    "reload_style_on_change": true,
    "layer": "top",
    "margin-top": 14,
    "margin-bottom": 0,
    //Load modules
    // "include": [
    //     "~/.config/waybar/modules.json"
    // ],
    //Modules LEFT
    "modules-left": [
        "clock",
        "wlr/taskbar",
    ],
    //Modules CENTER
    "modules-center": [
        "hyprland/workspaces",
    ],
    "clock": {
        "tooltip": true,
    },
    "hyprland/workspaces": {
        "persistent-workspaces": {
            "DP-1": [
                1,
                2,
                3
            ],
            "HDMI-A-1": [
                1,
                2,
                3
            ]
        },
        "format": "{icon}",
        "format-icons": {
            "active": "", //these two are icons from nerd fonts
            "default": ""
        },
    }
}

**Comment by tvannoy** [comment]
@msmafra What version of waybar are you using?

I'm using waybar v0.11.0 and I, like OP, have not been able to get the workspace icon colors to change via css. I resorted to using pango markup in the json config file.

**Comment by msmafra** [comment]
waybar 0.11.0
![2024-12-26-095551_hyprshot](https://github.com/user-attachments/assets/c4c4c46c-e671-40ab-82df-0b44e7b10fba)

**Comment by tvannoy** [comment]
@KiraKyatto Your config works fine for me:

![image](https://github.com/user-attachments/assets/b9a37441-b8f7-4c43-8e8a-40e197df2305)


I modified it for my monitor setup and hardcoded a color since we don't have your css colors.

**test.css**
```css
* {
        border: none;
        border-radius: 0;
        font-size: 18px;
        background: transparent;
        font-family: "BlexMono Nerd Font";
}

#workspaces button {
        padding: 0 5px;
        color: #31ade1;
}

.modules-center {
        background-color: #333333;
        border-radius: 15px;
        padding: 0 10px;
}
```

**test.jsonc**
```jsonc
{
        //Position TOP
        "layer": "top",
        "margin-top": 14,
        "margin-bottom": 0,

        //Load modules
        "include":["~/.config/waybar/modules.json"],

        //Modules LEFT
        "modules-left":[
                "clock",
                "wlr/taskbar",
        ],

        //Modules CENTER
        "modules-center":[
                "hyprland/workspaces",
        ],
}
```

**modules.json**
```jsonc
{
        "clock":{
                "tooltip": true,
        },
        "hyprland/workspaces":{
                "persistent-workspaces": {"*":[1,2,3],},
                "format": "{icon}",
                "format-icons":{
                        "active": "",  //these two are icons from nerd fonts
                        "default": ""
                },
        },
}
```


---


A slightly more involved minimal config from @msmafra's example:
**test.jsonc**
```jsonc
{
    //Position TOP
    "reload_style_on_change": true,
    "layer": "top",
    "margin-top": 14,
    "margin-bottom": 0,

    //Modules CENTER
    "modules-center": [
        "hyprland/workspaces",
    ],
    "hyprland/workspaces": {
        "persistent-workspaces": {
            "*": 3,
        },
        "format": "{icon}",
        "format-icons": {
        "active": "", //these two are icons from nerd fonts
        "default": ""
    },
    }
}
```

**test.css**
```css
* {
    border: none;
    border-radius: 0;
    font-size: 18px;
    background: transparent;
    font-family: "BlexMono Nerd Font";
}

#workspaces button {
    padding: 0 5px;
    color: #11e1ff;
}


#workspaces button:active {
    color: #555555;
}

#workspaces button.visible {
    color: #ffffff;
}

#workspaces button:hover {
    color: #ff0000;
}

.modules-center {
    background-color: #222222;
    border-radius: 15px;
    padding: 0 10px;
}
```

You can run it with `waybar -c ~/.config/waybar/test.jsonc -s ~/.config/waybar/test.css`

**Comment by tvannoy** [comment]
@KiraKyatto What version of waybar are you using?

Can you post a screenshot of what your bar looks like with your config?

Manually running waybar with an increased log-level might be worthwhile: `waybar -l debug`

**Comment by tvannoy** [comment]
Several other users were having the same issue of not being able to set hyprland workspace icons using css #2635 #3515 

I'm beginning to think that the issue was actually something in the [css order, as stated in the wiki](https://github.com/Alexays/Waybar/wiki/Module:-Hyprland#example-1), although I couldn't get the workspace icon colors working by following the wiki example.

**Comment by msmafra** [comment]
As I'm trying to keep my "environment" consistent and not pull my hair off :smiling_face_with_tear: . I try to reuse some of the CSS between the tools I use (nwg-drawer, wlgout, waybar etc).
I reset everything at the beginning and using REM instead of PX or other unit. The reset, the CSS ordering, some checks in the GTK3/4 CSS accepted properties side, using a non-monospaced font for symbols, solved other problems for me too like a unintended ghost colour effect when hovering buttons on my bar, some weird resizing also on hover etc.

```
@import url("palette.css");

* {
    all: unset;
    font-size: 16px;
    font-family: 'Inter Variable', 'Symbols Nerd Font';
    font-feature-settings: '"zero", "tnum", "ss01", "ss02", "ss03", "cv01", "cv05", "cv08", "cv10", "cv11", "cpsp", "case"';
    font-weight: 700;
    animation-timing-function: steps(12);
    animation-duration: 0.3s;
    transition: all 0.3s cubic-bezier(0.79, 0.33, 0.14, 0.53);
}
```

**Comment by KiraKyatto** [comment]
@tvannoy here are the screeshot you asked for 
![2025-01-02-140709_hyprshot](https://github.com/user-attachments/assets/6702ba1e-f95d-4a1e-9e9e-10497e26689b)
![2025-01-02-140747_hyprshot](https://github.com/user-attachments/assets/51bc8c37-080e-4c25-9d4b-d2915a7b91a0)

**Comment by msmafra** [comment]
> @tvannoy here are the screenshots you asked for ![2025-01-02-140709_hyprshot](https://private-user-images.githubusercontent.com/177319786/399707559-6702ba1e-f95d-4a1e-9e9e-10497e26689b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4NjIwMDgsIm5iZiI6MTczNTg2MTcwOCwicGF0aCI6Ii8xNzczMTk3ODYvMzk5NzA3NTU5LTY3MDJiYTFlLWY5NWQtNGExZS05ZTllLTEwNDk3ZTI2Njg5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMlQyMzQ4MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDhmOTc5YzBkZGFjZTFjNzExMWI3YjUzNzA5NDE5YTA0NDY1YzA2YjI4NDEyYTZhODI1M2I3NGJhN2M1MzFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kGBDXUTfdBVSoNDTStuZ4mCPhb5gfyy5_m0c6I4yVYw) ![2025-01-02-140747_hyprshot](https://private-user-images.githubusercontent.com/177319786/399707561-51bc8c37-080e-4c25-9d4b-d2915a7b91a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4NjIwMDgsIm5iZiI6MTczNTg2MTcwOCwicGF0aCI6Ii8xNzczMTk3ODYvMzk5NzA3NTYxLTUxYmM4YzM3LTA4MGUtNGMyNS05ZDRiLWQyOTE1YTdiOTFhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMlQyMzQ4MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Y2M0MGNlZGVmNGU4YzdmNWExNzE5YWQ5MjQzOGJkMTJiNjcxZWI0OGZiYjNhNDNkZjc3YjI2NWYwZjdiMjI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.txE2Wgm4uTA4KKuaXDSuAougrOrkYnSjCoobh5CBIEs)
> 
> and I also tried with hardcoded colors (same as yours to be sure) but it doesn't work

Please share your full waybar config (CSS and JSON).

**Comment by KiraKyatto** [comment]
Her are my config files : 

config.jsonc
```json
{
        //Position TOP
        "layer": "top",
        "margin-top": 14,
        "margin-bottom": 0,

        //Load modules
        "include":["~/.config/waybar/modules.json"],

        //Modules LEFT
        "modules-left":[
                "clock",
                "wlr/taskbar",
        ],

        //Modules CENTER
        "modules-center":[
                "hyprland/workspaces",
        ],

        //Modules RIGHT
        "modules-right":[
                "network",
        ]
}
```
modules.json

```json
{
        "clock":{
                "tooltip": true,
        },
        "hyprland/workspaces":{
                "persistent-workspaces": {"DP-1":[1,2,3], "HDMI-A-1":[1,2,3]},
                "format": "{icon}",
                "format-icons":{
                        "active": "",
                        "default": ""
                },
        },
        "network":{
                "format": "{bandwidthDownBits}    {bandwidthUpBits}  "
        },
}
```
style.css

```css
@import "/home/alex/.cache/wal/colors-waybar.css";

* {
        border: none;
        border-radius: 0;
        font-size: 18px;
        background: transparent;
}

#workspaces button {
        padding: 0 5px;
        color: @color2;
}


#network {
        font-size: 12px;
}

.modules-center, .modules-left, .modules-right {
        background-color: @color1;
        border-radius: 15px;
        padding: 0 10px;
}
```
colors-waybar.css

```css
@define-color foreground #dee1d5;
@define-color background #0f1421;
@define-color cursor #dee1d5;

@define-color color0 #0f1421;
@define-color color1 #75A39A;
@define-color color2 #9AAB9C;
@define-color color3 #B9B297;
@define-color color4 #C3B99B;
@define-color color5 #C4BDA2;
@define-color color6 #D1CDAE;
@define-color color7 #dee1d5;
@define-color color8 #9b9d95;
@define-color color9 #75A39A;
@define-color color10 #9AAB9C;
@define-color color11 #B9B297;
@define-color color12 #C3B99B;
@define-color color13 #C4BDA2;
@define-color color14 #D1CDAE;
@define-color color15 #dee1d5;
```
and here is what it looks like with this config : 
![2025-01-02-140747_hyprshot](https://github.com/user-attachments/assets/09e2d63c-45e7-43f3-84b6-5a7f596e532b)
