### ISSUE TITLE
rounded corners leaving a black background

### ISSUE THREAD

**Issue by dqrk0jeste** [Alexays/Waybar#3882]
setting a solid background color for window makes it appear beyond the rounded border corners. setting it to any transparent color does not. see pictures below.
it not that big of a problem, as i can set the opacity to 0.999 which makes no difference
![2025-01-13_22-11-01](https://github.com/user-attachments/assets/1c6c590a-b894-414e-8e32-4600b1343739)
![2025-01-13_22-11-14](https://github.com/user-attachments/assets/4bdf661a-f965-4145-91c9-f2fb517747d7)

**Comment by erffy** [comment]
Yeah, that happened to me.

**Comment by Crystal4276** [comment]
Try to add
```css
#waybar {
  background: transparent;
}
```

**Comment by diego-velez** [comment]
This is happening to me as well.

**Comment by Wyntino** [comment]
i encountered a similar issue on niri, switching from hexadecimal to rgba and setting it to 0.99 opacity ended up working for me

**Comment by Alexays** [comment]
This is the GTK opaque-region optimization: when a background is fully opaque, GTK fills the whole rectangle and `border-radius` on the top-level `window#waybar` does not clip it, so the corners stay solid. That is exactly why a sub-1.0 alpha (your `0.999` trick) works.

The clean fix is to keep the top-level window transparent and put your solid background + `border-radius` on a child container, which does clip correctly:

```css
window#waybar {
    background: transparent;
}

.modules-left, .modules-center, .modules-right {
    background-color: #2b303b;
    border-radius: 10px;
}
```

(or apply the background/radius to the individual `#module` widgets). Closing — reopen if it still bleeds past the corners. 🙏
