### ISSUE TITLE
privacy: missing css module class

### ISSUE THREAD

**Issue by czkz** [Alexays/Waybar#4034]
The following css is not applied to the privacy module, but it should be:

```css
.module {
  background-color: red;
}
```

This results in red background being visible on other modules, but not privacy.
