### ISSUE TITLE
A way to change style of another module when current module changes state

### ISSUE THREAD

**Issue by TheElevatedOne** [Alexays/Waybar#4064]
Hello, I am trying to make my waybar using powerline symbols. 

I am currently theming the battery module and I want to change the background of the battery module when charging, discharging, etc.

But, due to powerlines, I also need to change the background/color of them when the battery state changes and I cannot figure out how to achieve that.

Plugged in: 

![Image](https://github.com/user-attachments/assets/70f2867e-c80e-4fdf-a6ae-3b0ebebbb348)

Discharging: 

![Image](https://github.com/user-attachments/assets/59bf1cbb-3199-4cf8-a09c-ca15507fb12b)

---

I have been experimenting with
```css
#battery.discharging {
    background: #B76400;
    & #custom-rp-network { /* powerline on the left */
       background: #B76400;
    }
    & #custom-rp-battery { /* powerline on the right */
       color: #B76400;
    }
}
```

But it keeps throwing errors when launching waybar. Looking through [GTK3 CSS Overview](https://docs.gtk.org/gtk3/css-overview.html#selectors) didn't help either.

Is there someway to achieve this?

**Comment by TheElevatedOne** [comment]
Workaround: Used https://github.com/Alexays/Waybar/wiki/Configuration#multiple-instances-of-a-module, which was recommended to me by a user at https://github.com/Alexays/Waybar/discussions/4062#discussioncomment-12891784.

Renamed `battery` to `battery#main`, `custom/rp-network` to `battery#network` and `custom/rp-battery` to `battery#rp`.

It works, I just have three battery modules now.

---

Keeping this open if a real solution comes.

**Comment by Alexays** [comment]
This one isn't a Waybar limitation but a GTK3 one:

- GTK3's CSS engine doesn't support nesting or the `&` selector (that's GTK4 / modern-CSS), which is why `#battery.discharging { & #custom-rp-network { … } }` throws parse errors on launch.
- Each module is a separate top-level widget, so there's no selector that lets one module's state (`.discharging`) reach a *sibling* module.

The idiomatic workaround — which you already found 👍 — is to make the powerline arrows extra instances of the same module (`battery#main`, `battery#network`, `battery#rp`). They all receive the `.charging`/`.discharging` state class at the same time, so you can style them together:

```css
#battery.discharging { background: #B76400; }
```

That's the recommended approach for exactly this powerline pattern, so I'll close this out. Reopen if something doesn't work. 🙏
