### ISSUE TITLE
Issues with negative margin

### ISSUE THREAD

**Issue by xxennexx** [Alexays/Waybar#4176]
Possibly related: #3237

> [!NOTE]
> In the below screenshots, I've applied a `1px solid red` border to all .module elements, to further illustrate the situation.

Here is an example of my Waybar in a normal condition:
![Image](https://github.com/user-attachments/assets/bd069013-4ba7-4adc-970f-b5edd29b5f95)

When a "background color" changes (in this case, the battery background color changed from white to green), this happens:
![Image](https://github.com/user-attachments/assets/eccbfd45-773b-44ff-94c3-6bd494c90cbd)

When the `margin-left: -11px;` is removed, everything works as expected without the bug.
![Image](https://github.com/user-attachments/assets/9dffef2e-5cb8-4022-bc43-d74d03e86fb5)

Here are the relevant styles from my `style.css` (also available on [TailWind Play](https://play.tailwindcss.com/xYlovgMIyC) as an interactive (colorful) example):
```css
.modules-right > widget > .module {
    margin-left: -11px;
    padding-left: 16px;
    padding-right: 20px;

    /* PowerLine border */
    background-size: 11px 50%, 11px 50%, 11px 50%, 11px 50%, calc(100% - 22px) 100%;
    background-position: left top, left bottom, right top, right bottom, center;
    background-repeat: no-repeat;
}

#tray {
    background-image: linear-gradient(to left top, @tray_color 50%, transparent 50%),
        linear-gradient(to left bottom, @tray_color 50%, transparent 50%),
        linear-gradient(to right bottom, @tray_color 50%, transparent 50%),
        linear-gradient(to right top, @tray_color 50%, transparent 50%),
        linear-gradient(@tray_color, @tray_color);
}

#pulseaudio {
    background-image: linear-gradient(to left top, @pulseaudio_color 50%, transparent 50%),
        linear-gradient(to left bottom, @pulseaudio_color 50%, transparent 50%),
        linear-gradient(to right bottom, @pulseaudio_color 50%, transparent 50%),
        linear-gradient(to right top, @pulseaudio_color 50%, transparent 50%),
        linear-gradient(@pulseaudio_color, @pulseaudio_color);
}
```
