### ISSUE TITLE
Workspaces background unexpectedly turns white

### ISSUE THREAD

**Issue by jajo-11** [Alexays/Waybar#468]
The background of Workspaces turns white but only if i have only chromium in that workspace.

Here is the workspaces part of my style.css

```css
#workspaces
{
    background: transparent;
    margin-top: 1px;
    margin-left: 2px;
    padding-bottom: 1px;
}
#workspaces button
{
    color: darkgray;
}
 #workspaces button.focused
{
    color: white;
}
 #workspaces button:hover {
    box-shadow: inherit;
    text-shadow: inherit;
    color: #58abb7;
    background: transparent;
}
 #workspaces button.urgent {
    background-color: #f77923;
}
```

![image](https://user-images.githubusercontent.com/2552188/65374696-068e4f80-dc8d-11e9-9d17-a3d60c2dd6c5.png)

As evident in the style.css the background should be transparent like the rest of the bar.

**Comment by Alexays** [comment]
Are your background white?

**Comment by jajo-11** [comment]
No. All my backgrounds are set to "transparent". This is how the Workspaces area looks like when chromium is not open:

![image](https://user-images.githubusercontent.com/2552188/65393914-a5977200-dd87-11e9-8a33-9682ecbebae5.png)

**Comment by Alexays** [comment]
Ahh i see, you must have the following block.
```css
window#waybar.chromium {
    background-color: #000000;
    border: none;
}
```

Or something like that, no?
