### ISSUE TITLE
Request: Style sway/window with empty workspace

### ISSUE THREAD

**Issue by forkbomb9** [Alexays/Waybar#488]
It would be nice to be able to change the background of the sway/window module when no windows are present:

```css
#window {
    background: rgba(12, 12, 12, 0.4);
    color: #e5e5e5;
    padding-left: 10px;
    padding-right: 10px;
    border-radius: 15px;
}

#window.empty {
    background: rgba(12, 12, 12, 0.0);
}
```

Right now, it looks weird...
![2019-10-21-150408_screenshot](https://user-images.githubusercontent.com/33267474/67239156-3491bb80-f414-11e9-9c8b-fd5f67e98d40.png)
![2019-10-21-150432_screenshot](https://user-images.githubusercontent.com/33267474/67239164-378cac00-f414-11e9-9503-52651bec8afb.png)

**Comment by Alexays** [comment]
You can do this with
```css
window#waybar.empty #window {
	background: rgba(12, 12, 12, 0.0);
}
```
