### ISSUE TITLE
Disable hover/prelight effect on workspace buttons by default

### ISSUE THREAD

**Issue by jeremejevs** [Alexays/Waybar#60]
There's some default GTK CSS for the hover effect which I personally find unappealing, and I think many would concur. I've mitigated it by adding this rule:

```css
#workspaces button:hover {
  box-shadow: inherit;
  text-shadow: inherit;
}
```

Maybe this could be done out of the box? Alternatively, prelight could be disabled altogether, but I think some may want to have hover effects.

**Comment by Alexays** [comment]
I close this, it's documented in the wiki :)

**Comment by shasherazi** [comment]
Hello, I tried the given CSS, but the hover effect is still visible
![image](https://user-images.githubusercontent.com/63230301/233573946-374a712f-a879-4378-bb7b-4120a5b0a61c.png)

With this CSS tho

```css
#workspaces button:hover {
    background: none;
    border: none;
}
```

The hover effect is gone, but there is still a very slight dimming of the icon on the hover. It's not a big deal, but you can't unsee it once you see it.

![image](https://user-images.githubusercontent.com/63230301/233574400-063520b9-fc41-4044-b49c-dca2cb0be88b.png)

Here the 5th workspace is very slightly dimmed coz I was hovering over it. It's not noticeable unless you know it.

**Comment by matijabozic** [comment]
Had the same issue and solved it with these CSS properties: 
```
button:hover {
  box-shadow: none; /* Remove predefined box-shadow */
  text-shadow: none; /* Remove predefined text-shadow */
  background: none; /* Remove predefined background color (white) */
  transition: none; /* Disable predefined animations */
}
```
`background: none;` property is important as without it you can't set `background-color` through `#workspaces button:hover` selector. Whatever color you set there, it defaults to white which is not defined in Waybar's style.css. Also, `transition: none;` removes CSS hover animation. 

I know it's an old issue that's closed, but feel it would be nice if this would be changed. Default style.css does not allow you to change background  color through  `#workspaces button:hover` selector and defaults to white color, until you set background to none in `button:hover` selector. And that white color is not defined in style.css but coming from GTK CSS.

Anyways, its solvable with these CSS properties, but it would be nicer if it would work like this out of the box. 
And we can always use CSS animations to animate hover effect of buttons.

**Comment by Mr-Pine** [comment]
I think one of 
```css
#workspaces button:hover {
  border-color: transparent;
}

#workspaces button {
  border: none;
}
```
is the nicest solution so far. Also, this doesn't seem to be in the wiki anymore (or I just didn't find it)

**Comment by kingprawn22** [comment]
> Had the same issue and solved it with these CSS properties:
> 
> ```
> button:hover {
>   box-shadow: none; /* Remove predefined box-shadow */
>   text-shadow: none; /* Remove predefined text-shadow */
>   background: none; /* Remove predefined background color (white) */
>   transition: none; /* Disable predefined animations */
> }
> ```
> 
> `background: none;` property is important as without it you can't set `background-color` through `#workspaces button:hover` selector. Whatever color you set there, it defaults to white which is not defined in Waybar's style.css. Also, `transition: none;` removes CSS hover animation.
> 
> I know it's an old issue that's closed, but feel it would be nice if this would be changed. Default style.css does not allow you to change background color through `#workspaces button:hover` selector and defaults to white color, until you set background to none in `button:hover` selector. And that white color is not defined in style.css but coming from GTK CSS.
> 
> Anyways, its solvable with these CSS properties, but it would be nicer if it would work like this out of the box. And we can always use CSS animations to animate hover effect of buttons if we want to.

Thanks for this. Of the multiple solutions provided, this one works best for me to get an *almost* blank canvas when creating my own style. It's a shame we have to use such a workaround.

**Comment by lx78WyY0J5** [comment]
Confirmed, a shame to add CSS to remove **__UNWANTED__** CSS...

**Comment by grolongo** [comment]
@lx78WyY0J5 agree, the default should be no CSS. maybe a quick PR can fix this.

**Comment by goldmark00000** [comment]
version GTK+ 3.24.51
I was editing my status bar's style and i saw, using the gtk css debugger, more css style that i didn't write about the class _#workspaces button_.

I used these lines of css to overwrite them.
These lines overwrite the **default hover effect** too.

```css
/* to disable some default styles */
#workspaces button {

    background: none;
    border: none;
    padding: 0;
    text-shadow: none;
    box-shadow: none;
    transition: none;
    -gtk-icon-shadow: none;
    -gtk-icon-effect: none;

}
/* end */
```
