### ISSUE TITLE
sway window#waybar.solo triggers on a split

### ISSUE THREAD

**Issue by ralsei** [Alexays/Waybar#671]
To reproduce, use CSS like:

```css
window {
  color:      #c2c2b0;
  background: rgba(34, 34, 34, 0.00);
}
window#waybar.solo {
  color:      #c2c2b0;
  background: rgba(34, 34, 34, 0.85);
}
```

Then [in Sway] open two windows, create a vertical split, and open and close a window. The style for `waybar.solo` triggers even though there are two workspaces.

Example provided at https://qtp2t.club/pub/waybar.mp4. Using Sway 1.4 and Waybar 0.9.0 under Void Linux.
