### ISSUE TITLE
Waybar "jumps" if css has border-bottom

### ISSUE THREAD

**Issue by heroin-moose** [Alexays/Waybar#694]
For some reason latest Waybar from git "jumps" if CSS has the following code:

```CSS
#workspaces button.focused {
    border-bottom: 1.5pt;
}
```

Waybar 0.8.0 works fine though.

**Comment by heroin-moose** [comment]
CSS file:

```CSS
* {
    min-height: 0;

    border: none;
    border-radius: 0;

    color: #383c36;
    background: #fbf1c7;

    font-family: "Fantasque Sans Mono", "Font Awesome 5 Free Solid";
    font-size: 13pt;
}

window#waybar {
    padding: 0pt 5pt 0pt;
}

#backlight,
#battery,
#clock,
#mode,
#network,
#pulseaudio,
#workspaces {
    margin-right: 15pt;
}

#mode {
    color: #fbf1c7;
    background: #d79921;
}

#pulseaudio.muted {
    color: #d5c4a1;
}

#workspaces button {
    font-weight: bold;
    padding: 3pt 5pt 3pt;
    min-width: 20pt;
}

#workspaces button:hover {
    box-shadow: inherit;
    text-shadow: inherit;
}

#workspaces button.focused {
    margin-top: 1.5pt;
    border-bottom: 1.5pt solid #427b58;
}
```
