### ISSUE TITLE
cannot change color for workspaces button.focused border-bottom

### ISSUE THREAD

**Issue by zimbipw** [Alexays/Waybar#748]
Hi there I have this in my styles.css:
#workspaces button {
    padding:    0 5px;
    color:      rgba(23, 147, 209, 0.4);
    border-bottom: 3px solid rgba(23, 147, 209, 0.4);
}
#workspaces button.focused {
    border-top: 3px solid rgba(23, 147, 209, 1);
    border-bottom: 3px solid rgba(23, 147, 209, 1);
}
It's ok for the unfocused workspaces where I have the Arch blue but not on the focuse workspace  where the bottom border remains white.

**Comment by Alexays** [comment]
The white line under the focused workspace isn't a `border-bottom` — the default `style.css` draws it with an inset box-shadow so the text isn't offset:

```css
#workspaces button.focused {
    box-shadow: inset 0 -3px #ffffff;
}
```

Your `border-bottom` is being drawn under that box-shadow. Override the box-shadow (or set it to your color) instead of the border:

```css
#workspaces button.focused {
    box-shadow: inset 0 -3px rgba(23, 147, 209, 1);
    /* or: box-shadow: none;  and then your border-bottom will show */
}
```

Closing, but reopen if it still won't take. 🙏
