### ISSUE TITLE
Wide workspace buttons

### ISSUE THREAD

**Issue by Bryophyllum** [Alexays/Waybar#83]
Changing `workspaces button`'s `padding` to `0 0px` does not make it any narrower beside Sway's built-in `swaybar`. I expect them to at least be as narrow as sway's workspace buttons.  Do I do something wrong, is it a bug or intended?
![2018-11-04-143657_grim](https://user-images.githubusercontent.com/27376783/47964799-26019700-e03f-11e8-8b0f-1dd4862b6241.png)
By the way, my screen resolution is 1366 by 768.

**Comment by Alexays** [comment]
Can you provide your whole css file, on my side if i set padding to 0, it's very thin.

**Comment by Bryophyllum** [comment]
@Alexays I doubt it'll be neccessary. It's the same case for the default css file with no changes made to the config file as well:
![2018-11-04-201352_grim](https://user-images.githubusercontent.com/27376783/47968744-31b88200-e06e-11e8-99e7-834af8618d9a.png)

**Comment by Alexays** [comment]
![image](https://user-images.githubusercontent.com/13947260/48007937-eeffb400-e118-11e8-9237-b2582a82933b.png)
I have no idea, if I set padding to 0 it's okay :?
```css
* {
    border: none;
    border-radius: 0;
    font-family: Roboto, Helvetica, Arial, sans-serif;
    font-size: 13px;
    min-height: 0;
}

window#waybar {
    background: rgba(43, 48, 59, 0.5);
    border-bottom: 3px solid rgba(100, 114, 125, 0.5);
    color: white;
}

#workspaces button {
    padding: 0;
    background: transparent;
    color: white;
    border-bottom: 3px solid transparent;
}

#workspaces button.focused {
    background: #64727D;
    border-bottom: 3px solid white;
}

#mode {
    background: #64727D;
    border-bottom: 3px solid white;
}

#clock, #battery, #cpu, #memory, #network, #pulseaudio, #custom-spotify, #tray, #mode {
    padding: 0 10px;
    margin: 0 5px;
}

#clock {
    background-color: #64727D;
}

#battery {
    background-color: #ffffff;
    color: black;
}

#battery.charging {
    color: white;
    background-color: #26A65B;
}

@keyframes blink {
    to {
        background-color: #ffffff;
        color: black;
    }
}

#battery.warning:not(.charging) {
    background: #f53c3c;
    color: white;
    animation-name: blink;
    animation-duration: 0.5s;
    animation-timing-function: linear;
    animation-iteration-count: infinite;
    animation-direction: alternate;
}

#cpu {
    background: #2ecc71;
    color: #000000;
}

#memory {
    background: #9b59b6;
}

#network {
    background: #2980b9;
}

#network.disconnected {
    background: #f53c3c;
}

#pulseaudio {
    background: #f1c40f;
    color: black;
}

#pulseaudio.muted {
    background: #90b1b1;
    color: #2a5c45;
}

#custom-spotify {
    background: #66cc99;
    color: #2a5c45;
}

#tray {
    background-color: #2980b9;
}
```

**Comment by Bryophyllum** [comment]
![2018-11-05-164546_grim](https://user-images.githubusercontent.com/27376783/48008620-55390680-e11a-11e8-9bc4-d44ae6915cf6.png)
With the style css you provided it does not shrink significantly.. Is there a way I could help debugging this? I get no errors when I run it from the terminal or recompile it against the newest, freshly-compiled git version of Sway.

**Comment by Alexays** [comment]
@Bryophyllum Yep try with Gtk inspector

**Comment by Bryophyllum** [comment]
I ran `GTK_DEBUG=interactive waybar`, now what? What should I look for? I've never used GTK Inspector before.

**Comment by Bryophyllum** [comment]
I think I figured it out: I changed the GTK theme from Adapta-ETA to GNOME's Adwaita and it's now narrower than Sway's workspace buttons. Weird. I would have not guessed that if I had to pinpoint the issue based on some statistics, etc from GTK Inspector.
![2018-11-05-170552_grim](https://user-images.githubusercontent.com/27376783/48010044-1bb5ca80-e11d-11e8-94c3-b4973c2e372e.png)

**Comment by Alexays** [comment]
Did you try to put  !important ?

**Comment by Bryophyllum** [comment]
No, I did not. Besides, I randomly tried switching GTK themes and I still have no idea how to either use or debug with it. Anyway, isn't this considered solved by now? The issue was the theme that forced the workspace buttons' lenght.

**Comment by Bryophyllum** [comment]
In any case, thank you for taking your time to help me. c:

**Comment by memchr** [comment]
The reason for this may be that some GTK themes set `min-width` of `button.text-button.flat`. Overriding this property in waybar's `style.css' should fix this. The wiki has been updated to reflect this.

```css
#workspaces button {
  min-width: 20px;
}
```
