### ISSUE TITLE
Pulseaudio sink/source confusion

### ISSUE THREAD

**Issue by hanckmann** [Alexays/Waybar#839]
Hi,

The volume of pulseaudio#source and pulseaudio#sink are not separated.

I use this inside my config
```
...
"modules-right": ["pulseaudio#sink", "pulseaudio#source", "backlight", "network", "cpu", "memory", "custom/storage", "battery"]
...

    "pulseaudio#sink": {
        //"scroll-step": 1,
        "format": "{volume}% {icon}",
        "format-muted": "🔇",
        "format-bluetooth": "{volume}% {icon}  {format_source}",
        "format-icons": {
            "headphones": [" ", " ", " "],
            "handsfree": "",
            "headset":  [" ", " ", " "],
            "phone": [" ", " ", " "],
            "portable": [" ", " ", " "],
            "car": [" ", " ", " "],
            "default": ["", "", ""]
        },
        "on-click": "pactl set-sink-mute @DEFAULT_SINK@ toggle",
        "on-click-right": "/usr/bin/pavucontrol",
        "on-scroll-down": "pactl set-sink-volume @DEFAULT_SINK@ -1%",
        "on-scroll-up": "pactl set-sink-volume @DEFAULT_SINK@ +1%"
    },
    "pulseaudio#source": {
        "format-source": "{volume}% {icon}",
        "format-source-muted": "",
        "format-icons": [""],
        "on-click": "pactl set-source-mute @DEFAULT_SOURCE@ toggle",
        "on-click-right": "/usr/bin/pavucontrol",
        "on-scroll-down": "pactl set-source-volume @DEFAULT_SOURCE@ -1%",
        "on-scroll-up": "pactl set-source-volume @DEFAULT_SOURCE@ +1%"
    },
...
```

There are multiple issues:
- the source volume is not shown, instead it shows the sink volume,
- scrolling on the sink volume changes the sink volume (as expected), scrolling on the source volume does not work,
- the source mute state is not shown/detected,
- when the sink is muted, ths source is not muted.

I think the pulseaudio#source shows and does what pulseaudio#sink shows and does, with the exception of the icon and the muted state.
Hence, I am really lost in what is wrong with my configuration or with the application.

**Comment by cristobaltapia** [comment]
In your `pulseaudio#source` you have to add `"format": "{format_source}"` as:

```yaml
"pulseaudio#source": {
        "format" : "{format_source}",
        "format-source": "{volume}% {icon}",
        "format-source-muted": "",
        "format-icons": [""],
        "on-click": "pactl set-source-mute @DEFAULT_SOURCE@ toggle",
        "on-click-right": "/usr/bin/pavucontrol",
        "on-scroll-down": "pactl set-source-volume @DEFAULT_SOURCE@ -1%",
        "on-scroll-up": "pactl set-source-volume @DEFAULT_SOURCE@ +1%"
    },
```

That should help with the volume not being correctly shown for the source. The only problem I have with this configuration is that the mute state of the source is not detected, as you also have pointed out. I mean, it is detected and the correct icon is shown, however, the mute style defined in the `style.css` file is not applied.

**Comment by hanckmann** [comment]
Your solution seems to help partially. It now does not show the #sink information anymore.
However there are two issues remaining:

- The #sink always shows as muted in the bar (no matter the actual state, it shows the muted icon). The scroll wheel does change the mic volume (so that works), but the visuals are not updated.
- It is throwing the following error message:

```
[2020-11-03 09:42:54.122] [error] pulseaudio#source: argument not found
```

The pulseaudio#source part now looks like:

```
    "pulseaudio#source": {
        "format": "{format_source}",
        "format-source": "{volume}% {icon}",
        "format-source-muted": "",
        "format-icons": [""],
        "on-click": "pactl set-source-mute @DEFAULT_SOURCE@ toggle",
        "on-click-right": "/usr/bin/pavucontrol",
        "on-scroll-down": "pactl set-source-volume @DEFAULT_SOURCE@ -1%",
        "on-scroll-up": "pactl set-source-volume @DEFAULT_SOURCE@ +1%"
    },
```

**Comment by cristobaltapia** [comment]
This is my configuration, maybe it helps:

```yaml
    "pulseaudio#mic": {
      "format": "{format_source}",
      "format-source": "{volume}% ",
      "format-source-muted": "",
      "on-click": "pactl set-source-mute alsa_input.pci-0000_00_1b.0.analog-stereo toggle",
      "on-scroll-up": "pactl set-source-volume alsa_input.pci-0000_00_1b.0.analog-stereo +5%",
      "on-scroll-down": "pactl set-source-volume alsa_input.pci-0000_00_1b.0.analog-stereo -5%"
    }

```
