### ISSUE TITLE
Cannot set a different font for the tray menu

### ISSUE THREAD

**Issue by itaranto** [Alexays/Waybar#915]
Overriding the font for the tray object does not work. For example:
```css
#tray {
    font-family: Some Font;
}
```

However, overriding does work in other components like clock:
```css
#clock {
    font-family: Some Font;
}
```
