### ISSUE TITLE
Height and overlay configuration?

### ISSUE THREAD

**Issue by dorgnarg** [Alexays/Waybar#958]
I have a waybar that I'm running as my standard sway statusbar, but I'm trying to make an extra sidebar that I can call with a shortcut (correct me if this isn't really possible with waybar), and I'm running into 2 issues:
1. I'm trying to change the height (to make the top be below my existing waybar status bar), but setting "height" in my config hasn't done the trick. Can anyone help me figure out why this isn't working as intended?
2. I'd like it to be an overlay for what's already on the window, but right now it's shifting everything over as if it's a dock. Is this the only option or is there a way of changing this behavior?

Here are my config and stylesheet:
```json
{
    "layer": "top",
    "position": "left",
    "height": 500,
    "width": 320,
    "modules-left": ["clock#date","clock#time", "battery"],
    "clock#date": {
        "format": "{:%a %b %d, %Y}"
    },
    "clock#time": {
        "format": "{:%H:%M}"
    },
    "battery": {
        "format": "{icon}",
        "format-icons": ["", "", "", "" ],
        "format-charging": " {capacity}%",
        "states": {
            "happy": 100,
            "ok": 45,
            "sad": 20,
            "critical": 5
        }
    },
}
```

```css
@define-color bg #040501;
@define-color fg #cccccc;
@define-color color0 #2d2d2d;
@define-color color1 #f2777a;
@define-color color2 #99cc99;
@define-color color3 #ffcc66;
@define-color color4 #6699cc;
@define-color color5 #cc99cc;
@define-color color6 #66cccc;
@define-color color7 #cccccc;
@define-color color8 #999999;
@define-color color9 #f99157;
@define-color color10 #393939;
@define-color color11 #515151;
@define-color color12 #b4b7b4;
@define-color color13 #e0e0e0;
@define-color color14 #a3685a;
@define-color color15 #ffffff;

* {
    border: none;
    /* min-height: 0; */
    font-family: sans;
    font-size: 18px;
    background-color: @bg;
    color: @fg;
    border-radius: 0 80px 0 0;
}

#clock {
    font-family: display;
    font-size: 44pt;
    margin: 14pt 0
}

#clock.date {
    font-size: 14pt;
    margin-top: 44pt;
}

#battery {
    font-family: typicons;
    font-size: 64pt;
}

#battery.happy {
    color: @color2;
}

#battery.ok {
    color: @color3;
}

#battery.sad {
    color: @color1;
}

#battery.critical {
    color: @color1;
}

#battery.charging {
    color: black;
}
```
